USE RegisterCases
GO
--SELECT TOP 10 * FROM vw_sprCSGRules

SELECT distinct code,MSCondition
		,CASE WHEN DS1 IS NULL THEN 0 ELSE 1 END AS DS1
		,CASE WHEN DS2 IS NULL THEN 0 ELSE 1 END AS DS2
		,CASE WHEN DS3 IS NULL THEN 0 ELSE 1 END AS DS3
		,CASE WHEN MUSurgery IS NULL THEN 0 ELSE 1 END AS MUSurgery
		,CASE WHEN Age IS NULL THEN 0 ELSE 1 END AS Age
		,CASE WHEN Sex IS NULL THEN 0 ELSE 1 END AS Sex
		,CASE WHEN Los IS NULL THEN 0 ELSE 1 END AS Los
		,CASE WHEN rf_idAddCretiria IS NULL THEN 0 ELSE 1 END AS rf_idAddCretiria
		,CASE WHEN fraction IS NULL THEN 0 ELSE 1 END AS fraction
FROM vw_sprCSGRules 
ORDER BY code