USE RegisterCases
GO
--SELECT TOP 10 * FROM vw_sprCSGRules

IF OBJECT_ID('sprBitCSGRules','U') IS NOT NULL
	DROP TABLE sprBitCSGRules
go
SELECT distinct code AS CodeCSG,MSCondition AS USL_OK
		,cast(CASE WHEN DS1 IS NULL THEN 0 ELSE 1 END AS BIT) AS DS1
		,cast(CASE WHEN DS2 IS NULL THEN 0 ELSE 1 END AS BIT) AS DS2
		,cast(CASE WHEN DS3 IS NULL THEN 0 ELSE 1 END AS BIT) AS DS3
		,cast(CASE WHEN MUSurgery IS NULL THEN 0 ELSE 1 END AS BIT) AS MUSurgery
		,cast(CASE WHEN Age IS NULL THEN 0 ELSE 1 END AS BIT) AS Age
		,cast(CASE WHEN SexId IS NULL THEN 0 ELSE 1 END AS BIT) AS Sex
		,cast(CASE WHEN Los IS NULL THEN 0 ELSE 1 END AS BIT) AS Los
		,cast(CASE WHEN rf_idAddCretiria IS NULL THEN 0 ELSE 1 END AS BIT) AS rf_idAddCretiria
		,cast(CASE WHEN fraction IS NULL THEN 0 ELSE 1 END AS BIT) AS fraction
INTO sprBitCSGRules
FROM vw_sprCSGRules 
ORDER BY CodeCSG
GO
CREATE NONCLUSTERED INDEX QU_CSG_USL_OK ON sprBitCSGRules(CodeCSG,USL_OK)