USE [PolicyRegister]
GO

/****** Object:  Index [IX_PEOPLE_IM_OT_DR_DOCN_Case]    Script Date: 03.10.2017 9:21:09 ******/
--CREATE NONCLUSTERED INDEX [IX_PEOPLE_IM_OT_DR_DOCN_Case] ON [dbo].[PEOPLE]
--(
--	[DOCN] ASC
--)
--INCLUDE ( 	[IM],
--	[OT],
--	[DR],
--	[FAM],
--	[PID],
--	[W],ID,FAME,IME,OTE,MR) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


--/****** Object:  Index [IX_PEOPLE_SS_FAM_DOCN_IM_DR_Case]    Script Date: 03.10.2017 9:40:53 ******/
--CREATE NONCLUSTERED INDEX [IX_PEOPLE_SS_FAM_DOCN_IM_DR_Case] ON [dbo].[PEOPLE]
--(
--	[SS] ASC,
--	[FAM] ASC,
--	[IM] ASC,
--	[OT] ASC,
--	[DR] ASC,
--	[DOCN] ASC
--)
--INCLUDE ( 	[PID],
--	[W],FAME,IME,OTE) WITH (DROP_EXISTING = ON, ONLINE = ON) ON [PRIMARY]
--GO

--CREATE NONCLUSTERED INDEX [IX_PEOPLE_ENP_MY] ON [dbo].[PEOPLE]
--(
--	[ENP] ASC
--)
--INCLUDE ( 	[DR],
--	[FAM],
--	[IM],
--	[OT],FAME,IME,OTE,NPOL) WITH (DROP_EXISTING = ON, ONLINE =ON) ON [PRIMARY]
--GO

--CREATE NONCLUSTERED INDEX [IX_PEOPLE_SS_FAM_DOCN_IM_DR_Case] ON [dbo].[PEOPLE]
--(
--	[SS] ASC,
--	[FAM] ASC,
--	[IM] ASC,
--	[OT] ASC,
--	[DR] ASC,
--	[DOCN] ASC
--)
--INCLUDE ( 	[PID],
--	[W],
--	[FAME],
--	[IME],
--	[OTE],MR) WITH (DROP_EXISTING = on, ONLINE = OFF) ON [PRIMARY]
--GO

--CREATE NONCLUSTERED INDEX [IX_PEOPLE_DPFS] ON [dbo].[PEOPLE]
--(
--	[NPOL] ASC,
--	[SPOL] ASC
--) INCLUDE(FAM,IM,OT,FAME,IME,OTE,DR,ENP)WITH (DROP_EXISTING =ON, ONLINE = OFF) ON [PRIMARY]
--GO


/****** Object:  Index [IX_HISTSS_PID]    Script Date: 03.10.2017 10:43:57 ******/
--CREATE NONCLUSTERED INDEX [IX_HISTSS_PID] ON [dbo].[HISTSS]
--(
--	[PID] ASC
--) INCLUDE(SS) WITH (DROP_EXISTING = ON, ONLINE = OFF) ON [PRIMARY]
--GO

--CREATE NONCLUSTERED INDEX [IX_HISTSS_PID_MY] ON [dbo].[HISTSS]
--(
--	SS ASC
--) INCLUDE(PID) WITH (DROP_EXISTING = ON, ONLINE = OFF) ON [PRIMARY]
--GO
USE [PolicyRegister]
GO

/****** Object:  Index [IX_POLIS_PID]    Script Date: 03.10.2017 11:14:10 ******/
--CREATE NONCLUSTERED INDEX [IX_POLIS_PID] ON [dbo].[POLIS]
--(
--	[PID] ASC
--)
--INCLUDE ( 	[Q],
--	[DBEG],
--	[POLTP],
--	[SPOL],
--	[NPOL],
--	[DSTOP],
--	[OKATO],
--	[DEND],ST) WITH (DROP_EXISTING = ON, ONLINE = OFF) ON [PRIMARY]
GO

--CREATE NONCLUSTERED INDEX [IX_HISTLPU_PID] ON [dbo].[HISTLPU]
--(
--	[PID] ASC
--)
--INCLUDE ( 	[LPUDT],
--	[LPU],ID) WITH (DROP_EXISTING = ON, ONLINE = OFF) ON [PRIMARY]
GO








