SET QUOTED_IDENTIFIER ON
go
---------------------------------------------------------1------------------------------------------------------

IF  EXISTS (SELECT * FROM sys.indexes WHERE OBJECT_ID = OBJECT_ID(N'dbo.HISTUDL') AND name = N'IX_HISTUDL_DOCN')
	DROP INDEX IX_HISTUDL_DOCN ON dbo.HISTUDL 

GO

CREATE NONCLUSTERED INDEX IX_HISTUDL_DOCN ON dbo.HISTUDL(PID) 
INCLUDE(DOCN) WITH ( ONLINE = ON, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO
---------------------------------------------------------2------------------------------------------------------
IF  EXISTS (SELECT * FROM sys.indexes WHERE OBJECT_ID = OBJECT_ID(N'dbo.HISTFDR') AND name = N'IX_HISTFDR_FAM_IM_OT_DR')
DROP INDEX IX_HISTFDR_FAM_IM_OT_DR ON dbo.HISTFDR 

GO
CREATE NONCLUSTERED INDEX IX_HISTFDR_FAM_IM_OT_DR ON dbo.HISTFDR(PID,FAM,IM,OT,DR,w)  
WITH ( ONLINE = ON, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) 
GO
----------------------------------------------------------3-----------------------------------------------------
IF  EXISTS (SELECT * FROM sys.indexes WHERE OBJECT_ID = OBJECT_ID(N'dbo.PEOPLE') AND name = N'IX_PEOPLE_DR')
DROP INDEX IX_PEOPLE_DR ON dbo.PEOPLE
 
GO
CREATE NONCLUSTERED INDEX IX_PEOPLE_DR ON dbo.PEOPLE 
(
	DR ASC,
	IM
)INCLUDE(FAM,OT,PID,W,ID,FAME,IME,OTE,MR) WITH ( ONLINE = ON, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) 
GO
-----------------------------------------------------------4----------------------------------------------------
IF  EXISTS (SELECT * FROM sys.indexes WHERE OBJECT_ID = OBJECT_ID(N'dbo.PEOPLE') AND name = N'IX_PEOPLE_FIODR_DOCN_Cases')
DROP INDEX IX_PEOPLE_FIODR_DOCN_Cases ON dbo.PEOPLE
 
GO
CREATE NONCLUSTERED INDEX IX_PEOPLE_FIODR_DOCN_Cases ON dbo.PEOPLE 
(
	FAM ASC,
	IM ASC,
	OT ASC,
	DR ASC
)
INCLUDE ( DOCN,PID,W) WITH ( ONLINE = ON, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) 
GO
------------------------------------------------------------5---------------------------------------------------
IF  EXISTS (SELECT * FROM sys.indexes WHERE OBJECT_ID = OBJECT_ID(N'dbo.PEOPLE') AND name = N'IX_PEOPLE_IM_OT_DR_DOCN_Case')
DROP INDEX IX_PEOPLE_IM_OT_DR_DOCN_Case ON dbo.PEOPLE 

GO
CREATE NONCLUSTERED INDEX [IX_PEOPLE_IM_OT_DR_DOCN_Case] ON [dbo].[PEOPLE]
(
	[DOCN] ASC
)
INCLUDE ( 	[IM],
	[OT],
	[DR],
	[FAM],
	[PID],
	[W],ID,FAME,IME,OTE,MR) WITH ( ONLINE = ON, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) 
GO
-------------------------------------------------------------6--------------------------------------------------
IF  EXISTS (SELECT * FROM sys.indexes WHERE OBJECT_ID = OBJECT_ID(N'dbo.PEOPLE') AND name = N'IX_PEOPLE_SS_FAM_OT_IM_Case')
DROP INDEX IX_PEOPLE_SS_FAM_OT_IM_Case ON dbo.PEOPLE 

GO
CREATE NONCLUSTERED INDEX IX_PEOPLE_SS_FAM_OT_IM_Case ON dbo.PEOPLE 
(
	SS ASC,
	FAM ASC,
	IM ASC,
	OT ASC
)
INCLUDE ( DR,PID,W) WITH ( ONLINE = ON, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) 
GO
--------------------------------------------------------------7-------------------------------------------------
IF  EXISTS (SELECT * FROM sys.indexes WHERE OBJECT_ID = OBJECT_ID(N'dbo.PEOPLE') AND name = N'IX_PEOPLE_SS_FAM_DOCN_IM_DR_Case')
DROP INDEX IX_PEOPLE_SS_FAM_DOCN_IM_DR_Case ON dbo.PEOPLE
 
GO
CREATE NONCLUSTERED INDEX [IX_PEOPLE_SS_FAM_DOCN_IM_DR_Case] ON [dbo].[PEOPLE]
(
	[SS] ASC,
	[FAM] ASC,
	[IM] ASC,
	[OT] ASC,
	[DR] ASC,
	[DOCN] ASC
)
INCLUDE ( 	[PID],
	[W],
	[FAME],
	[IME],
	[OTE],MR) WITH ( ONLINE = ON, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) 
GO
---------------------------------------------------------------8------------------------------------------------
IF  EXISTS (SELECT * FROM sys.indexes WHERE OBJECT_ID = OBJECT_ID(N'dbo.POLIS') AND name = N'IX_POLIS_PID')
DROP INDEX IX_POLIS_PID ON dbo.POLIS 

GO
CREATE NONCLUSTERED INDEX IX_POLIS_PID ON dbo.POLIS 
(
	PID ASC
)
INCLUDE(Q,DBEG,POLTP,SPOL,NPOL,DSTOP,OKATO,DEND) WITH ( ONLINE = ON) 
GO
----------------------------------------------------------------9-----------------------------------------------
IF  EXISTS (SELECT * FROM sys.indexes WHERE OBJECT_ID = OBJECT_ID(N'dbo.HISTFDR') AND name = N'IX_HISTFDR_PID')
DROP INDEX IX_HISTFDR_PID ON dbo.HISTFDR 

GO
CREATE NONCLUSTERED INDEX IX_HISTFDR_PID ON dbo.HISTFDR 
(
	PID ASC
)
INCLUDE(FAM,OT,IM,DR,W) WITH ( ONLINE = ON, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) 
GO
-----------------------------------------------------------------10----------------------------------------------
IF  EXISTS (SELECT * FROM sys.indexes WHERE OBJECT_ID = OBJECT_ID(N'dbo.HISTFDR') AND name = N'IX_HISTFDR_FIODR')
DROP INDEX IX_HISTFDR_FIODR ON dbo.HISTFDR
GO
CREATE NONCLUSTERED INDEX IX_HISTFDR_FIODR ON dbo.HISTFDR 
(
	FAM ASC,
	IM ASC,
	OT ASC,
	W ASC,
	DR ASC
)
INCLUDE(PID) WITH ( ONLINE = ON, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) 
GO
-------------------------------------------------------------------11--------------------------------------------
IF  EXISTS (SELECT * FROM sys.indexes WHERE OBJECT_ID = OBJECT_ID(N'dbo.HISTLPU') AND name = N'IX_HISTLPU_PID')
DROP INDEX IX_HISTLPU_PID ON dbo.HISTLPU 

GO
CREATE NONCLUSTERED INDEX IX_HISTLPU_PID ON dbo.HISTLPU 
(
	PID ASC
)
INCLUDE(LPUDT,LPU) WITH (STATISTICS_NORECOMPUTE  = ON,  ONLINE = ON, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) 

GO

IF  EXISTS (SELECT * FROM sys.indexes WHERE OBJECT_ID = OBJECT_ID(N'dbo.HISTFDR') AND name = N'IX_HISTFDR_FIO_Sex_ID')
DROP INDEX IX_HISTFDR_FIO_Sex_ID ON dbo.HISTFDR 
go
CREATE NONCLUSTERED INDEX IX_HISTFDR_FIO_Sex_ID
ON [dbo].[HISTFDR] ([FAM],[IM],[DR])
INCLUDE ([ID],[OT],[W]) WITH (STATISTICS_NORECOMPUTE  = ON,  ONLINE = ON, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
go

IF  EXISTS (SELECT * FROM sys.indexes WHERE OBJECT_ID = OBJECT_ID(N'dbo.PEOPLE') AND name = N'IX_PEOPLE_ENP_MY')
DROP INDEX IX_PEOPLE_ENP_MY ON dbo.PEOPLE
GO
CREATE NONCLUSTERED INDEX [IX_PEOPLE_ENP_MY] ON [dbo].[PEOPLE]
(
	[ENP] ASC
)
INCLUDE ( 	[DR],
	[FAM],
	[IM],
	[OT],FAME,IME,OTE,NPOL) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE OBJECT_ID = OBJECT_ID(N'dbo.HISTENP') AND name = N'IX_HISTENP_ENP_My')
DROP INDEX IX_HISTENP_ENP_My ON dbo.HISTENP
GO
CREATE NONCLUSTERED INDEX [IX_HISTENP_ENP_My] ON [dbo].[HISTENP]
(
	[ENP] ASC
) INCLUDE(PID) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE OBJECT_ID = OBJECT_ID(N'PEOPLE') AND name = N'IX_ENP_FIO_ID')
DROP INDEX IX_ENP_FIO_ID ON dbo.PEOPLE 
GO
CREATE NONCLUSTERED INDEX IX_ENP_FIO_ID
ON [dbo].[PEOPLE] ([ENP])
INCLUDE ([FAM],[IM],[OT],[DR],[DS],[RN],[ID])
go
IF  EXISTS (SELECT * FROM sys.indexes WHERE OBJECT_ID = OBJECT_ID(N'HISTUDL') AND name = N'IX_HISTUDL_DOCN_MY')
DROP INDEX IX_HISTUDL_DOCN_MY ON dbo.HISTUDL 
GO
CREATE NONCLUSTERED INDEX [IX_HISTUDL_DOCN_MY] ON [dbo].[HISTUDL]
(
	[DOCN] ASC
)
INCLUDE (PID) 
WHERE DOCN IS not null
go
IF  EXISTS (SELECT * FROM sys.indexes WHERE OBJECT_ID = OBJECT_ID(N'PEOPLE') AND name = N'IX_PEOPLE_DPFS')
DROP INDEX IX_PEOPLE_DPFS ON dbo.PEOPLE
GO
CREATE NONCLUSTERED INDEX [IX_PEOPLE_DPFS] ON [dbo].[PEOPLE]
(
	[NPOL] ASC,
	[SPOL] ASC
) INCLUDE(FAM,IM,OT,FAME,IME,OTE,DR,ENP)
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE OBJECT_ID = OBJECT_ID(N'HISTSS') AND name = N'IX_HISTSS_PID')
DROP INDEX IX_HISTSS_PID ON dbo.HISTSS
GO
CREATE NONCLUSTERED INDEX IX_HISTSS_PID ON [dbo].[HISTSS]
(
	[PID] ASC
) INCLUDE(SS) 
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE OBJECT_ID = OBJECT_ID(N'HISTSS') AND name = N'IX_HISTSS_PID_MY')
DROP INDEX IX_HISTSS_PID_MY ON dbo.HISTSS
GO
CREATE NONCLUSTERED INDEX IX_HISTSS_PID_MY ON [dbo].[HISTSS]
(
	SS ASC
) INCLUDE(PID) 
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE OBJECT_ID = OBJECT_ID(N'POLIS') AND name = N'IX_POLIS_PID')
DROP INDEX IX_POLIS_PID ON dbo.POLIS
GO
CREATE NONCLUSTERED INDEX IX_POLIS_PID ON dbo.POLIS
(
	[PID] ASC
)
INCLUDE ( 	[Q],[DBEG],[POLTP],[SPOL],[NPOL],[DSTOP],[OKATO],[DEND],ST)
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE OBJECT_ID = OBJECT_ID(N'HISTLPU') AND name = N'IX_HISTLPU_PID')
DROP INDEX IX_HISTLPU_PID ON dbo.HISTLPU
GO
CREATE NONCLUSTERED INDEX IX_HISTLPU_PID ON dbo.HISTLPU
(
	[PID] ASC
)
INCLUDE ([LPUDT],[LPU],ID,LPUDX)
GO
