USE RegisterCases
GO
ALTER TABLE t_CaseDefine ADD id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY;
go
DBCC SHRINKFILE (N'account_log' , 0, TRUNCATEONLY)
GO
ALTER TABLE t_Diagnosis ADD id BIGINT IDENTITY(1,1) NOT NULL --PRIMARY KEY;
go
DBCC SHRINKFILE (N'account_log' , 0, TRUNCATEONLY)
GO
ALTER TABLE t_Error ADD id INT IDENTITY(1,1) NOT NULL PRIMARY KEY;
go
DBCC SHRINKFILE (N'account_log' , 0, TRUNCATEONLY)
GO
ALTER TABLE t_ErrorProcessControl ADD id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY;
go
DBCC SHRINKFILE (N'account_log' , 0, TRUNCATEONLY)
GO
ALTER TABLE t_Meduslugi ADD idPK BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY;
go	   
DBCC SHRINKFILE (N'account_log' , 0, TRUNCATEONLY)
GO
ALTER TABLE t_PatientBack ADD id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY;
go
DBCC SHRINKFILE (N'account_log' , 0, TRUNCATEONLY)
GO
ALTER TABLE t_RegisterPatientAttendant ADD id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY;
go
DBCC SHRINKFILE (N'account_log' , 0, TRUNCATEONLY)
GO
ALTER TABLE t_RegisterPatientDocument ADD id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY;
go
DBCC SHRINKFILE (N'account_log' , 0, TRUNCATEONLY)
GO
----------------------------------Add PK------------------------------
ALTER TABLE t_MES ADD CONSTRAINT PK_t_MES PRIMARY KEY NONCLUSTERED(rf_idCase);
go
DBCC SHRINKFILE (N'account_log' , 0, TRUNCATEONLY)
GO

ALTER TABLE t_PlanOrdersReport ADD CONSTRAINT PK_t_PlanOrdersReport PRIMARY KEY NONCLUSTERED(rf_idFile,rf_idFileBack,UnitCode);
go
DBCC SHRINKFILE (N'account_log' , 0, TRUNCATEONLY)
GO
ALTER TABLE t_RefRegisterPatientRecordCase ADD CONSTRAINT PK_RefRegisterPatientRecordCase PRIMARY KEY NONCLUSTERED(rf_idRecordCase,rf_idRegisterPatient);
go
DBCC SHRINKFILE (N'account_log' , 0, TRUNCATEONLY)
GO
ALTER TABLE t_PatientSMO ADD CONSTRAINT PK_t_PatientSMO PRIMARY KEY NONCLUSTERED(ref_idRecordCase);
go
DBCC SHRINKFILE (N'account_log' , 0, TRUNCATEONLY)
GO

ALTER TABLE t_CasePatientDefineIteration
ADD CONSTRAINT PK_t_CaseDefineIteration PRIMARY KEY CLUSTERED(rf_idRefCaseIteration,rf_idIteration);
GO
DBCC SHRINKFILE (N'account_log' , 0, TRUNCATEONLY)
GO