USE OMS_NSI
GO
grant select on object::V_sprV006 to db_NSI
grant select on object::tQuarter to db_NSI
grant select on object::vw_sprT001_A to db_NSI
grant select on object::V_sprV008 to db_NSI
grant select on object::sprNomenclMUUnGroup to db_NSI
grant select on object::V_sprV009 to db_NSI
grant select on object::sysdiagrams to db_NSI
grant select on object::V_sprV010 to db_NSI
grant select on object::sprV018 to db_NSI
grant select on object::sprV005 to db_NSI
grant select on object::V_sprV012 to db_NSI
grant select on object::tUser to db_NSI
grant select on object::V_sprVMPffoms to db_NSI
grant select on object::sprSpecialCase to db_NSI
grant select on object::sprSMODisable to db_NSI
grant select on object::V_sprVMPtfoms to db_NSI
grant select on object::tSmoExceptionReason to db_NSI
grant select on object::V_T001 to db_NSI
grant select on object::sprNomenclMU to db_NSI
grant select on object::V_TFOMS to db_NSI
grant select on object::tLicense to db_NSI
grant select on object::V_VP to db_NSI
grant select on object::sprV019 to db_NSI
grant select on object::sprV006 to db_NSI
grant select on object::V001 to db_NSI
grant select on object::sprMUGroup to db_NSI
grant select on object::View_1 to db_NSI
grant select on object::sprMUWithAge to db_NSI
grant select on object::View_1LN to db_NSI
grant select on object::tSmoNotice to db_NSI
grant select on object::vw_sprMU to db_NSI
grant select on object::sprNomenclMUtype to db_NSI
grant select on object::vw_sprCompletedCasePatientAge to db_NSI
grant select on object::tLicenseLocation to db_NSI
grant select on object::vw_sprMUAll to db_NSI
grant select on object::sprV019MKB to db_NSI
grant select on object::sprV008 to db_NSI
grant select on object::vw_sprMUAllOnce to db_NSI
grant select on object::sprMUUnGroup to db_NSI
grant select on object::vw_sprT001 to db_NSI
grant select on object::sprRefAccountLetterV009 to db_NSI
grant select on object::vw_sprCompletedCaseCSGTariff to db_NSI
grant select on object::sprControlType to db_NSI
grant select on object::V_MSLocation to db_NSI
grant select on object::tmpValidMU to db_NSI
grant select on object::vw_CSGPlanUnit to db_NSI
grant select on object::tLicenseStatus to db_NSI
grant select on object::tValidCSG to db_NSI
grant select on object::sprV009 to db_NSI
grant select on object::sprVMPtfoms to db_NSI
grant select on object::tMUPlanUnit to db_NSI
grant select on object::sprPaymentAccountCanceled to db_NSI
grant select on object::sprDepartmentalMembership to db_NSI
grant select on object::tPropTFOMS to db_NSI
grant select on object::tLicensePeriod to db_NSI
grant select on object::sprR010 to db_NSI
grant select on object::sprV010 to db_NSI
grant select on object::tAccountType to db_NSI
grant select on object::tPlanUnitPeriod to db_NSI
grant select on object::sprDocumentType to db_NSI
grant select on object::sprDiagnosisType to db_NSI
grant select on object::tRegionTFOMS to db_NSI
grant select on object::tMonth to db_NSI
grant select on object::sprTypeCheckup to db_NSI
grant select on object::sprR011 to db_NSI
grant select on object::sprOrderCheckup to db_NSI
grant select on object::sprV012 to db_NSI
grant select on object::sprTypeExamination to db_NSI
grant select on object::tMSCondition to db_NSI
grant select on object::sprTypePaymentDocument to db_NSI
grant select on object::tCSGConfirmLevel to db_NSI
grant select on object::sprF012 to db_NSI
grant select on object::V_LDSCC to db_NSI
grant select on object::tMUCondition to db_NSI
grant select on object::tmpLicensePeriod to db_NSI
grant select on object::View_zarya to db_NSI
grant select on object::sprR012 to db_NSI
grant select on object::Life_sprCompletedCasePatientDay to db_NSI
grant select on object::tPaymentMethod to db_NSI
grant select on object::tCSGType to db_NSI
grant select on object::sprInsuranceFactDocumentType to db_NSI
grant select on object::sprAllErrors to db_NSI
grant select on object::tmpMO to db_NSI
grant select on object::VLN_sMU to db_NSI
grant select on object::sprV015 to db_NSI
grant select on object::Life_sprMU to db_NSI
grant select on object::tPlanUnit to db_NSI
grant select on object::tHealingType to db_NSI
grant select on object::sprInsuredPersonStatus to db_NSI
grant select on object::tNoticePeriod to db_NSI
grant select on object::tMSForm to db_NSI
grant select on object::tMSBedProfile to db_NSI
grant select on object::Life_sprMUGroup to db_NSI
grant select on object::sprMU to db_NSI
grant select on object::tCSGroup to db_NSI
grant select on object::sprMedicalSpeciality to db_NSI
grant select on object::tmp_sprCompletedCasePatientDay to db_NSI
grant select on object::tMSLocation to db_NSI
grant select on object::tCSGV008Relation to db_NSI
grant select on object::TMP_MU to db_NSI
grant select on object::Life_sprMUUnGroup to db_NSI
grant select on object::tKLADRRegion to db_NSI
grant select on object::sprCompletedCaseDiagnosis to db_NSI
grant select on object::tKLADRArea to db_NSI
grant select on object::tCSGManagement to db_NSI
grant select on object::sprMO to db_NSI
grant select on object::tKLADRCity to db_NSI
grant select on object::tmp_sprMKBInOMS to db_NSI
grant select on object::fn_PlanOrders to db_NSI
grant select on object::tKLADRStreet to db_NSI
grant select on object::tMSPeriod to db_NSI
grant select on object::V_PeriodInOMS to db_NSI
grant select on object::sprMUPriceIndexing to db_NSI
grant select on object::V_sprMU to db_NSI
grant select on object::tMedicalService to db_NSI
grant select on object::V_MUCondition to db_NSI
grant select on object::tCSGMKB to db_NSI
grant select on object::sprOKATO to db_NSI
grant select on object::V_MUMedicalSpeciality to db_NSI
grant select on object::V_MUProfileAndPayment to db_NSI
grant select on object::tmp_sprMU to db_NSI
grant select on object::MSpeer_lsns to db_NSI
grant select on object::T002 to db_NSI
grant select on object::tmpMSPeriod to db_NSI
grant select on object::T003 to db_NSI
grant select on object::sprMUPriceIndexingOp to db_NSI
grant select on object::T004 to db_NSI
grant select on object::tDocSpecGroup to db_NSI
grant select on object::V_ExceptionReason to db_NSI
grant select on object::tCSGNomenclMU to db_NSI
grant select on object::sprIdentityCard to db_NSI
grant select on object::sprOKFS to db_NSI
grant select on object::V_License to db_NSI
grant select on object::MSpeer_request to db_NSI
grant select on object::V_LicenseLocation to db_NSI
grant select on object::tmp_sprMUGroup to db_NSI
grant select on object::V_LicenseLocationMO to db_NSI
grant select on object::tSMO to db_NSI
grant select on object::MSpeer_response to db_NSI
grant select on object::V_LicenseMSForm to db_NSI
grant select on object::MSpeer_topologyrequest to db_NSI
grant select on object::tRole to db_NSI
grant select on object::V_LicensePeriod to db_NSI
grant select on object::tMUAgeAndProfile to db_NSI
grant select on object::V_LicenseStatus to db_NSI
grant select on object::tCSGResourceConsuming to db_NSI
grant select on object::MSpeer_topologyresponse to db_NSI
grant select on object::sprOKOPF to db_NSI
grant select on object::V_MO to db_NSI
grant select on object::MSpeer_originatorid_history to db_NSI
grant select on object::v_MO_tf to db_NSI
grant select on object::tmp_sprMUPrice to db_NSI
grant select on object::V_MOFirstLvl to db_NSI
grant select on object::tmpSMO to db_NSI
grant select on object::MSpeer_conflictdetectionconfigrequest to db_NSI
grant select on object::V_MOSecondLvl to db_NSI
grant select on object::tSysObject to db_NSI
grant select on object::V_MOValidMU to db_NSI
grant select on object::sprCompletedCasePatientDay to db_NSI
grant select on object::V_MOValidMUGroup to db_NSI
grant select on object::tCSGAgeAndDocSpec to db_NSI
grant select on object::sprOKSM to db_NSI
grant select on object::V_MOValidMUUnGroup to db_NSI
grant select on object::V_sprMKB to db_NSI
grant select on object::V_MSCondition to db_NSI
grant select on object::tmp_sprMUPriceAVO to db_NSI
grant select on object::V_MSLevel to db_NSI
grant select on object::tSmoLicense to db_NSI
grant select on object::MSpeer_conflictdetectionconfigresponse to db_NSI
grant select on object::V_MSPricePeriod to db_NSI
grant select on object::tUserRole to db_NSI
grant select on object::V_Notice to db_NSI
grant select on object::tCityArea to db_NSI
grant select on object::V_NoticePeriod to db_NSI
grant select on object::tCSGAgeAndProfile to db_NSI
grant select on object::sprOKVED to db_NSI
grant select on object::V_OKOPF to db_NSI
grant select on object::tBedProfile to db_NSI
grant select on object::V_PlanCorrection to db_NSI
grant select on object::tmp_sprMUPriceModernization to db_NSI
grant select on object::V_PlanYear to db_NSI
grant select on object::tSmoLicensePeriod to db_NSI
grant select on object::V_ReestrMOReport to db_NSI
grant select on object::tValidMU to db_NSI
grant select on object::V_ReestrMOToExcel to db_NSI
grant select on object::tExceptionReason to db_NSI
grant select on object::V_reportCompletedCaseDiagnosis to db_NSI
grant select on object::tCSGBasePrice to db_NSI
grant select on object::sprPayStatus to db_NSI
grant select on object::V_reportCompletedCasePatientDay to db_NSI
grant select on object::V_reportGroupMU to db_NSI
grant select on object::tmp_sprMUUnGroup to db_NSI
grant select on object::sprMUWithAge2 to db_NSI
grant select on object::V_reportIndividualTarif to db_NSI
grant select on object::tmpSmoLicensePeriod to db_NSI
grant select on object::V_reportMKB to db_NSI
grant select on object::sprMUPriceModernization to db_NSI
grant select on object::V_ReportMODetails to db_NSI
grant select on object::tFilial to db_NSI
grant select on object::V_ReportMOLicense to db_NSI
grant select on object::tCSGLevel to db_NSI
grant select on object::sprSMO to db_NSI
grant select on object::MSreplication_subscriptions to db_NSI
grant select on object::V_ReportMO to db_NSI
grant select on object::V_reportMU to db_NSI
grant select on object::tmpMUAgeAndProfile to db_NSI
grant select on object::MSsubscription_agents to db_NSI
grant select on object::V_reportTarif to db_NSI
grant select on object::tMSPricePeriod to db_NSI
grant select on object::V_sprMUUnGroup to db_NSI
grant select on object::sprErrorForAccount to db_NSI
grant select on object::V_reportUnGroupMU to db_NSI
grant select on object::tOKOPF to db_NSI
grant select on object::vw_Accounts_OKATO to db_NSI
grant select on object::V_SMO to db_NSI
grant select on object::tCSGPriceType to db_NSI
grant select on object::sprStateRF to db_NSI
grant select on object::v_SMO_tf to db_NSI
grant select on object::sprAgeGroup to db_NSI
grant select on object::V_SmoExceptionReason to db_NSI
grant select on object::tMUAgeAndDocSpec to db_NSI
grant select on object::MSreplication_objects to db_NSI
grant select on object::V_SmoLicense to db_NSI
grant select on object::tNotice to db_NSI
grant select on object::MSsnapshotdeliveryprogress to db_NSI
grant select on object::V_SmoLicensePeriod to db_NSI
grant select on object::sprMKBInOMS to db_NSI
grant select on object::V_SmoNotice to db_NSI
grant select on object::tVP to db_NSI
grant select on object::MSsavedforeignkeys to db_NSI
grant select on object::V_sprCompletedCaseDiagnosis to db_NSI
grant select on object::tCSGPrice to db_NSI
grant select on object::sprTerritory to db_NSI
grant select on object::MSsavedforeignkeycolumns to db_NSI
grant select on object::V_sprCompletedCasePatientDay to db_NSI
grant select on object::sprHead to db_NSI
grant select on object::MSsavedforeignkeyextendedproperties to db_NSI
grant select on object::V_sprCompletedCasePD to db_NSI
grant select on object::sprFinance to db_NSI
grant select on object::V_sprMKBPeriod to db_NSI
grant select on object::tPlanYear to db_NSI
grant select on object::V_sprMKBAll to db_NSI
grant select on object::sprMUPriceAVO to db_NSI
grant select on object::V_sprMKBGroup to db_NSI
grant select on object::tMO to db_NSI
grant select on object::V_sprMKBInOMS to db_NSI
grant select on object::tCSGMOPrice to db_NSI
grant select on object::sprTFOMS to db_NSI
grant select on object::V_sprMKBUnGroup to db_NSI
grant select on object::sprHeadUnGroup to db_NSI
grant select on object::V_sprMO to db_NSI
grant select on object::sprViewCalc to db_NSI
grant select on object::V_sprMUPriceIndividual to db_NSI
grant select on object::tPlan to db_NSI
grant select on object::OKATO_NAME to db_NSI
grant select on object::V_sprMOForIndividualTarif to db_NSI
grant select on object::tMedSpecToGroupRelation to db_NSI
grant select on object::sprNomenclMUClass to db_NSI
grant select on object::V_sprMOValidMU to db_NSI
grant select on object::tMSLevel to db_NSI
grant select on object::V_sprMUForCompletedCasePD to db_NSI
grant select on object::sprF014 to db_NSI
grant select on object::sprV002 to db_NSI
grant select on object::V_sprMUGroup to db_NSI
grant select on object::sprMKB to db_NSI
grant select on object::V_sprMUPrice to db_NSI
grant select on object::sprViewCalcDoc to db_NSI
grant select on object::V_sprMUPriceAVO to db_NSI
grant select on object::tPlanCorrection to db_NSI
grant select on object::V_sprMUPriceModernization to db_NSI
grant select on object::vw_sprOKATO to db_NSI
grant select on object::sprNomenclMUGroup to db_NSI
grant select on object::V_sprNomenclMUGroup to db_NSI
grant select on object::sprMUPrice to db_NSI
grant select on object::View_2 to db_NSI
grant select on object::V_sprNomenclMUUnGroup to db_NSI
grant select on object::sprV014 to db_NSI
grant select on object::sprV003 to db_NSI
grant select on object::V_sprProfile to db_NSI
grant select on object::DiagnosisType to db_NSI
grant select on object::V_sprV002 to db_NSI
grant select on object::sprViewDoc to db_NSI
grant select on object::Table_1 to db_NSI


------------------------------------------------------------------------------------------------------------------------------------------------------------------
grant insert on object::tQuarter to db_NSI
grant insert on object::sprNomenclMUUnGroup to db_NSI
grant insert on object::sysdiagrams to db_NSI
grant insert on object::sprV018 to db_NSI
grant insert on object::sprV005 to db_NSI
grant insert on object::tUser to db_NSI
grant insert on object::sprSpecialCase to db_NSI
grant insert on object::sprSMODisable to db_NSI
grant insert on object::tSmoExceptionReason to db_NSI
grant insert on object::sprNomenclMU to db_NSI
grant insert on object::tLicense to db_NSI
grant insert on object::sprV019 to db_NSI
grant insert on object::sprV006 to db_NSI
grant insert on object::sprMUGroup to db_NSI
grant insert on object::sprMUWithAge to db_NSI
grant insert on object::tSmoNotice to db_NSI
grant insert on object::sprNomenclMUtype to db_NSI
grant insert on object::tLicenseLocation to db_NSI
grant insert on object::sprV019MKB to db_NSI
grant insert on object::sprV008 to db_NSI
grant insert on object::sprMUUnGroup to db_NSI
grant insert on object::sprRefAccountLetterV009 to db_NSI
grant insert on object::sprControlType to db_NSI
grant insert on object::tmpValidMU to db_NSI
grant insert on object::tLicenseStatus to db_NSI
grant insert on object::tValidCSG to db_NSI
grant insert on object::sprV009 to db_NSI
grant insert on object::sprVMPtfoms to db_NSI
grant insert on object::tMUPlanUnit to db_NSI
grant insert on object::sprPaymentAccountCanceled to db_NSI
grant insert on object::sprDepartmentalMembership to db_NSI
grant insert on object::tPropTFOMS to db_NSI
grant insert on object::tLicensePeriod to db_NSI
grant insert on object::sprR010 to db_NSI
grant insert on object::sprV010 to db_NSI
grant insert on object::tAccountType to db_NSI
grant insert on object::tPlanUnitPeriod to db_NSI
grant insert on object::sprDocumentType to db_NSI
grant insert on object::sprDiagnosisType to db_NSI
grant insert on object::tRegionTFOMS to db_NSI
grant insert on object::tMonth to db_NSI
grant insert on object::sprTypeCheckup to db_NSI
grant insert on object::sprR011 to db_NSI
grant insert on object::sprOrderCheckup to db_NSI
grant insert on object::sprV012 to db_NSI
grant insert on object::sprTypeExamination to db_NSI
grant insert on object::tMSCondition to db_NSI
grant insert on object::sprTypePaymentDocument to db_NSI
grant insert on object::tCSGConfirmLevel to db_NSI
grant insert on object::sprF012 to db_NSI
grant insert on object::tMUCondition to db_NSI
grant insert on object::tmpLicensePeriod to db_NSI
grant insert on object::sprR012 to db_NSI
grant insert on object::Life_sprCompletedCasePatientDay to db_NSI
grant insert on object::tPaymentMethod to db_NSI
grant insert on object::tCSGType to db_NSI
grant insert on object::sprInsuranceFactDocumentType to db_NSI
grant insert on object::sprAllErrors to db_NSI
grant insert on object::tmpMO to db_NSI
grant insert on object::sprV015 to db_NSI
grant insert on object::Life_sprMU to db_NSI
grant insert on object::tPlanUnit to db_NSI
grant insert on object::tHealingType to db_NSI
grant insert on object::sprInsuredPersonStatus to db_NSI
grant insert on object::tNoticePeriod to db_NSI
grant insert on object::tMSForm to db_NSI
grant insert on object::tMSBedProfile to db_NSI
grant insert on object::Life_sprMUGroup to db_NSI
grant insert on object::sprMU to db_NSI
grant insert on object::tCSGroup to db_NSI
grant insert on object::sprMedicalSpeciality to db_NSI
grant insert on object::tmp_sprCompletedCasePatientDay to db_NSI
grant insert on object::tMSLocation to db_NSI
grant insert on object::tCSGV008Relation to db_NSI
grant insert on object::TMP_MU to db_NSI
grant insert on object::Life_sprMUUnGroup to db_NSI
grant insert on object::tKLADRRegion to db_NSI
grant insert on object::sprCompletedCaseDiagnosis to db_NSI
grant insert on object::tKLADRArea to db_NSI
grant insert on object::tCSGManagement to db_NSI
grant insert on object::sprMO to db_NSI
grant insert on object::tKLADRCity to db_NSI
grant insert on object::tmp_sprMKBInOMS to db_NSI
grant insert on object::tKLADRStreet to db_NSI
grant insert on object::tMSPeriod to db_NSI
grant insert on object::sprMUPriceIndexing to db_NSI
grant insert on object::tMedicalService to db_NSI
grant insert on object::tCSGMKB to db_NSI
grant insert on object::sprOKATO to db_NSI
grant insert on object::tmp_sprMU to db_NSI
grant insert on object::MSpeer_lsns to db_NSI
grant insert on object::tmpMSPeriod to db_NSI
grant insert on object::sprMUPriceIndexingOp to db_NSI
grant insert on object::tDocSpecGroup to db_NSI
grant insert on object::tCSGNomenclMU to db_NSI
grant insert on object::sprIdentityCard to db_NSI
grant insert on object::sprOKFS to db_NSI
grant insert on object::MSpeer_request to db_NSI
grant insert on object::tmp_sprMUGroup to db_NSI
grant insert on object::tSMO to db_NSI
grant insert on object::MSpeer_response to db_NSI
grant insert on object::MSpeer_topologyrequest to db_NSI
grant insert on object::tRole to db_NSI
grant insert on object::tMUAgeAndProfile to db_NSI
grant insert on object::tCSGResourceConsuming to db_NSI
grant insert on object::MSpeer_topologyresponse to db_NSI
grant insert on object::sprOKOPF to db_NSI
grant insert on object::MSpeer_originatorid_history to db_NSI
grant insert on object::tmp_sprMUPrice to db_NSI
grant insert on object::tmpSMO to db_NSI
grant insert on object::MSpeer_conflictdetectionconfigrequest to db_NSI
grant insert on object::tSysObject to db_NSI
grant insert on object::sprCompletedCasePatientDay to db_NSI
grant insert on object::tCSGAgeAndDocSpec to db_NSI
grant insert on object::sprOKSM to db_NSI
grant insert on object::tmp_sprMUPriceAVO to db_NSI
grant insert on object::tSmoLicense to db_NSI
grant insert on object::MSpeer_conflictdetectionconfigresponse to db_NSI
grant insert on object::tUserRole to db_NSI
grant insert on object::tCityArea to db_NSI
grant insert on object::tCSGAgeAndProfile to db_NSI
grant insert on object::sprOKVED to db_NSI
grant insert on object::tBedProfile to db_NSI
grant insert on object::tmp_sprMUPriceModernization to db_NSI
grant insert on object::tSmoLicensePeriod to db_NSI
grant insert on object::tValidMU to db_NSI
grant insert on object::tExceptionReason to db_NSI
grant insert on object::tCSGBasePrice to db_NSI
grant insert on object::sprPayStatus to db_NSI
grant insert on object::tmp_sprMUUnGroup to db_NSI
grant insert on object::sprMUWithAge2 to db_NSI
grant insert on object::tmpSmoLicensePeriod to db_NSI
grant insert on object::sprMUPriceModernization to db_NSI
grant insert on object::tFilial to db_NSI
grant insert on object::tCSGLevel to db_NSI
grant insert on object::sprSMO to db_NSI
grant insert on object::MSreplication_subscriptions to db_NSI
grant insert on object::tmpMUAgeAndProfile to db_NSI
grant insert on object::MSsubscription_agents to db_NSI
grant insert on object::tMSPricePeriod to db_NSI
grant insert on object::sprErrorForAccount to db_NSI
grant insert on object::tOKOPF to db_NSI
grant insert on object::tCSGPriceType to db_NSI
grant insert on object::sprStateRF to db_NSI
grant insert on object::sprAgeGroup to db_NSI
grant insert on object::tMUAgeAndDocSpec to db_NSI
grant insert on object::MSreplication_objects to db_NSI
grant insert on object::tNotice to db_NSI
grant insert on object::MSsnapshotdeliveryprogress to db_NSI
grant insert on object::sprMKBInOMS to db_NSI
grant insert on object::tVP to db_NSI
grant insert on object::MSsavedforeignkeys to db_NSI
grant insert on object::tCSGPrice to db_NSI
grant insert on object::sprTerritory to db_NSI
grant insert on object::MSsavedforeignkeycolumns to db_NSI
grant insert on object::sprHead to db_NSI
grant insert on object::MSsavedforeignkeyextendedproperties to db_NSI
grant insert on object::sprFinance to db_NSI
grant insert on object::tPlanYear to db_NSI
grant insert on object::sprMUPriceAVO to db_NSI
grant insert on object::tMO to db_NSI
grant insert on object::tCSGMOPrice to db_NSI
grant insert on object::sprTFOMS to db_NSI
grant insert on object::sprHeadUnGroup to db_NSI
grant insert on object::sprViewCalc to db_NSI
grant insert on object::tPlan to db_NSI
grant insert on object::tMedSpecToGroupRelation to db_NSI
grant insert on object::sprNomenclMUClass to db_NSI
grant insert on object::tMSLevel to db_NSI
grant insert on object::sprF014 to db_NSI
grant insert on object::sprV002 to db_NSI
grant insert on object::sprMKB to db_NSI
grant insert on object::sprViewCalcDoc to db_NSI
grant insert on object::tPlanCorrection to db_NSI
grant insert on object::sprNomenclMUGroup to db_NSI
grant insert on object::sprMUPrice to db_NSI
grant insert on object::sprV014 to db_NSI
grant insert on object::sprV003 to db_NSI
grant insert on object::DiagnosisType to db_NSI
grant insert on object::sprViewDoc to db_NSI
grant insert on object::Table_1 to db_NSI