USE AccountOMS
GO

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
grant select on object::fn_GetCaseFromRegisterCaseDB to db_AccountOMS
grant select on object::tmp_AllCasesCSG to db_AccountOMS
grant select on object::tmp_Case to db_AccountOMS
grant select on object::vw_vkStac2012 to db_AccountOMS
grant select on object::vw_vkSprMedusluges to db_AccountOMS
grant select on object::tmp_CSG_20141226 to db_AccountOMS
grant select on object::vw_vkStac2011 to db_AccountOMS
grant select on object::t_FileError to db_AccountOMS
grant select on object::tmpMissingCase to db_AccountOMS
grant select on object::vw_vkDnst2012 to db_AccountOMS
grant select on object::tmpEqualCase to db_AccountOMS
grant select on object::vw_vkDnst2011 to db_AccountOMS
grant select on object::View_Pokatilov to db_AccountOMS
grant select on object::vw_vkAmbl2012 to db_AccountOMS
grant select on object::View_Otch1 to db_AccountOMS
grant select on object::vw_vkAmbl2011 to db_AccountOMS
grant select on object::vw_Случаи to db_AccountOMS
grant select on object::t_SystemError to db_AccountOMS
grant select on object::t_FileDelete to db_AccountOMS
grant select on object::t_Case_PID_ENP34 to db_AccountOMS
grant select on object::vw_vkStom2012 to db_AccountOMS
grant select on object::t_FileTested to db_AccountOMS
grant select on object::vw_vkStom2011 to db_AccountOMS
grant select on object::vw_vkTestAmbl2012 to db_AccountOMS
grant select on object::vw_summaDispanserizacia to db_AccountOMS
grant select on object::vw_СчетаДляСвязиСлучаев to db_AccountOMS
grant select on object::vw_ФайлыДляСлучаев to db_AccountOMS
grant select on object::vw_MeduslugiMes to db_AccountOMS
grant select on object::vw_МОДляСлучаев to db_AccountOMS
grant select on object::vw_ОКАТОДляСлучаев to db_AccountOMS
grant select on object::t_File to db_AccountOMS
grant select on object::View_5LN to db_AccountOMS
grant select on object::View_6LN to db_AccountOMS
grant select on object::t_FileSynch to db_AccountOMS
grant select on object::View_stom to db_AccountOMS
grant select on object::tmp_FileSynch to db_AccountOMS
grant select on object::vw_МОДляСлучаев2 to db_AccountOMS
grant select on object::vw_V001 to db_AccountOMS
grant select on object::t_Errors to db_AccountOMS
grant select on object::View_146 to db_AccountOMS
grant select on object::vw_sprMU to db_AccountOMS
grant select on object::vw_sprSMO to db_AccountOMS
grant select on object::vw_sprT001 to db_AccountOMS
grant select on object::View_146_2014 to db_AccountOMS
grant select on object::vw_sprMUCompletedCase to db_AccountOMS
grant select on object::vw_sprFilial to db_AccountOMS
grant select on object::q_VK_ReportHMP to db_AccountOMS
grant select on object::fn_GetDiagnosisRegisterCaseDB to db_AccountOMS
grant select on object::vw_DeleteMU to db_AccountOMS
grant select on object::vw_getIdFileNumber to db_AccountOMS
grant select on object::tmp_PeopleSex to db_AccountOMS
grant select on object::vw_SumByVid to db_AccountOMS
grant select on object::tmp_HelthDeartment to db_AccountOMS
grant select on object::vw_DoubleCase to db_AccountOMS
grant select on object::vw_ClinicalExaminationAdults to db_AccountOMS
grant select on object::t_RegisterPatient to db_AccountOMS
grant select on object::t_DoubleGuidCase to db_AccountOMS
grant select on object::t1 to db_AccountOMS
grant select on object::t_RegisterPatientDocumentTemp to db_AccountOMS
grant select on object::t_DoubleGuidCase2 to db_AccountOMS
grant select on object::t_RegistersAccounts to db_AccountOMS
grant select on object::t_FileKey to db_AccountOMS
grant select on object::View_SopDiagn to db_AccountOMS
grant select on object::t_pac123 to db_AccountOMS
grant select on object::View_usl to db_AccountOMS
grant select on object::t_FileExit to db_AccountOMS
grant select on object::View_146_1 to db_AccountOMS
grant select on object::vw_MagalazKireeva_34001 to db_AccountOMS
grant select on object::t_RecordCasePatient to db_AccountOMS
grant select on object::fn_GetMeduslugiFromRegisterCaseDB to db_AccountOMS
grant select on object::vw_Diagnosis to db_AccountOMS
grant select on object::vw_MagalazKireeva_34002 to db_AccountOMS
grant select on object::vw_getPatientDoc to db_AccountOMS
grant select on object::t_RegisterPatientDocument to db_AccountOMS
grant select on object::vw_sprSMO_Report to db_AccountOMS
grant select on object::t_RegisterPatientAttendant to db_AccountOMS
grant select on object::vw_sprMuWithParamAccount to db_AccountOMS
grant select on object::vw_sprT001_Report to db_AccountOMS
grant select on object::q_VK_ReportFP to db_AccountOMS
grant select on object::vw_TotalDoubleGUID to db_AccountOMS
grant select on object::View_ACC to db_AccountOMS
grant select on object::vw_MUCSGLetter to db_AccountOMS
grant select on object::vw_AFileInSMO34 to db_AccountOMS
grant select on object::t_Case to db_AccountOMS
grant select on object::t_uslug to db_AccountOMS
grant select on object::vw_146First to db_AccountOMS
grant select on object::vw_DFileInSMO34 to db_AccountOMS
grant select on object::vw_146Second to db_AccountOMS
grant select on object::t_146_5 to db_AccountOMS
grant select on object::View_PID_UDL to db_AccountOMS
grant select on object::vw_LA146_1 to db_AccountOMS
grant select on object::t_PatientSMO to db_AccountOMS
grant select on object::vw_LA146_2 to db_AccountOMS
grant select on object::t_FinancialSanctions to db_AccountOMS
grant select on object::t_Diagnosis to db_AccountOMS
grant select on object::t_Case_PID_ENP to db_AccountOMS
grant select on object::t_ReasonPaymentCancelled to db_AccountOMS
grant select on object::t_Meduslugi to db_AccountOMS
grant select on object::vw_sprMUAll to db_AccountOMS
grant select on object::t_MES to db_AccountOMS
grant select on object::T_146_6 to db_AccountOMS
grant select on object::t_People_Case to db_AccountOMS
grant select on object::t_AdditionalFilterRequests to db_AccountOMS
grant select on object::t_PaymentAcceptedCase to db_AccountOMS
grant select on object::t_PaidCase to db_AccountOMS
grant select on object::t_146_7 to db_AccountOMS
grant select on object::t_146_8 to db_AccountOMS
grant select on object::View_FAP to db_AccountOMS
grant select on object::vw_MUChild14D_Col6 to db_AccountOMS
grant select on object::View_1 to db_AccountOMS
grant select on object::vw_MUChild14D_Col7 to db_AccountOMS
grant select on object::vw_sprCSGWithParamAccount to db_AccountOMS
grant select on object::fn_PlanOrders to db_AccountOMS
grant select on object::View_1_FAP to db_AccountOMS
grant select on object::View_PID_ENP to db_AccountOMS
grant select on object::vw_PlanOrders2011 to db_AccountOMS
grant select on object::View_Patient to db_AccountOMS
grant select on object::t_AdditionalAccounts to db_AccountOMS
grant select on object::t_DeleteCase to db_AccountOMS
grant select on object::t_146 to db_AccountOMS
grant select on object::vw_AmountDeductionRAKLocal to db_AccountOMS
grant select on object::wv_AmountPaymentRPDLocal to db_AccountOMS
grant select on object::tmp_Diagnosis to db_AccountOMS
grant select on object::t_ln_d to db_AccountOMS
grant select on object::View_146_3 to db_AccountOMS
grant select on object::View_Otch11 to db_AccountOMS
grant select on object::View_Otch2 to db_AccountOMS
grant select on object::view_sprMonth to db_AccountOMS
grant select on object::View_Otch3 to db_AccountOMS
grant select on object::View_Child_U to db_AccountOMS
grant select on object::view_MO to db_AccountOMS
grant select on object::vw_sprMKB10 to db_AccountOMS
grant select on object::view_sprTFOMS to db_AccountOMS
grant select on object::tmp_PeopleIteration2 to db_AccountOMS
grant select on object::view_sprRegionTFOMS to db_AccountOMS
grant select on object::view_sprV002 to db_AccountOMS
grant select on object::view_sprV004 to db_AccountOMS
grant select on object::view_sprV008 to db_AccountOMS
grant select on object::view_sprV009 to db_AccountOMS
grant select on object::t_ProvideConditions to db_AccountOMS
grant select on object::view_sprV010 to db_AccountOMS
grant select on object::view_sprV006 to db_AccountOMS
grant select on object::sysdiagrams to db_AccountOMS
grant select on object::view_sprV012 to db_AccountOMS
grant select on object::view_Mes to db_AccountOMS
grant select on object::view_xCase to db_AccountOMS
grant select on object::t_FileUser to db_AccountOMS
grant select on object::view_sprMU to db_AccountOMS
grant select on object::view_Meduslugi to db_AccountOMS
grant select on object::view_MKB to db_AccountOMS
grant select on object::view_sprF011 to db_AccountOMS
grant select on object::fn_iter_intlist_to_table to db_AccountOMS
grant select on object::vw_sprCSG to db_AccountOMS
grant select on object::View_VA to db_AccountOMS
grant select on object::vw_testAccounts to db_AccountOMS
grant select on object::tmp_NotMatchedLetterMU to db_AccountOMS
grant select on object::tmp_CSG to db_AccountOMS
grant select on object::t_va to db_AccountOMS
grant select on object::vw_unitName to db_AccountOMS
grant select on object::sprDiagnosisKSG to db_AccountOMS
grant select on object::tmp_sprCSG to db_AccountOMS
grant select on object::t_UserPermissions to db_AccountOMS
grant select on object::sprGroupKSG to db_AccountOMS
grant select on object::sprMUSurgeryKSG to db_AccountOMS
grant select on object::vw_sprAllError to db_AccountOMS
grant select on object::t_BirthWeight to db_AccountOMS


-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
grant insert on object::tmp_AllCasesCSG to db_AccountOMS
grant insert on object::tmp_Case to db_AccountOMS
grant insert on object::tmp_CSG_20141226 to db_AccountOMS
grant insert on object::t_FileError to db_AccountOMS
grant insert on object::tmpMissingCase to db_AccountOMS
grant insert on object::tmpEqualCase to db_AccountOMS
grant insert on object::t_SystemError to db_AccountOMS
grant insert on object::t_FileDelete to db_AccountOMS
grant insert on object::t_Case_PID_ENP34 to db_AccountOMS
grant insert on object::t_FileTested to db_AccountOMS
grant insert on object::t_File to db_AccountOMS
grant insert on object::t_FileSynch to db_AccountOMS
grant insert on object::tmp_FileSynch to db_AccountOMS
grant insert on object::t_Errors to db_AccountOMS
grant insert on object::tmp_PeopleSex to db_AccountOMS
grant insert on object::tmp_HelthDeartment to db_AccountOMS
grant insert on object::t_RegisterPatient to db_AccountOMS
grant insert on object::t_DoubleGuidCase to db_AccountOMS
grant insert on object::t1 to db_AccountOMS
grant insert on object::t_RegisterPatientDocumentTemp to db_AccountOMS
grant insert on object::t_DoubleGuidCase2 to db_AccountOMS
grant insert on object::t_RegistersAccounts to db_AccountOMS
grant insert on object::t_FileKey to db_AccountOMS
grant insert on object::t_pac123 to db_AccountOMS
grant insert on object::t_FileExit to db_AccountOMS
grant insert on object::t_RecordCasePatient to db_AccountOMS
grant insert on object::t_RegisterPatientDocument to db_AccountOMS
grant insert on object::t_RegisterPatientAttendant to db_AccountOMS
grant insert on object::t_Case to db_AccountOMS
grant insert on object::t_uslug to db_AccountOMS
grant insert on object::t_146_5 to db_AccountOMS
grant insert on object::t_PatientSMO to db_AccountOMS
grant insert on object::t_FinancialSanctions to db_AccountOMS
grant insert on object::t_Diagnosis to db_AccountOMS
grant insert on object::t_Case_PID_ENP to db_AccountOMS
grant insert on object::t_ReasonPaymentCancelled to db_AccountOMS
grant insert on object::t_Meduslugi to db_AccountOMS
grant insert on object::t_MES to db_AccountOMS
grant insert on object::T_146_6 to db_AccountOMS
grant insert on object::t_People_Case to db_AccountOMS
grant insert on object::t_AdditionalFilterRequests to db_AccountOMS
grant insert on object::t_PaymentAcceptedCase to db_AccountOMS
grant insert on object::t_PaidCase to db_AccountOMS
grant insert on object::t_146_7 to db_AccountOMS
grant insert on object::t_146_8 to db_AccountOMS
grant insert on object::t_AdditionalAccounts to db_AccountOMS
grant insert on object::t_DeleteCase to db_AccountOMS
grant insert on object::t_146 to db_AccountOMS
grant insert on object::tmp_Diagnosis to db_AccountOMS
grant insert on object::t_ln_d to db_AccountOMS
grant insert on object::tmp_PeopleIteration2 to db_AccountOMS
grant insert on object::t_ProvideConditions to db_AccountOMS
grant insert on object::sysdiagrams to db_AccountOMS
grant insert on object::t_FileUser to db_AccountOMS
grant insert on object::tmp_NotMatchedLetterMU to db_AccountOMS
grant insert on object::tmp_CSG to db_AccountOMS
grant insert on object::t_va to db_AccountOMS
grant insert on object::sprDiagnosisKSG to db_AccountOMS
grant insert on object::tmp_sprCSG to db_AccountOMS
grant insert on object::t_UserPermissions to db_AccountOMS
grant insert on object::sprGroupKSG to db_AccountOMS
grant insert on object::sprMUSurgeryKSG to db_AccountOMS
grant insert on object::t_BirthWeight to db_AccountOMS


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
grant execute on object::fn_MonthName to db_AccountOMS
grant execute on object::usp_selectLPU to db_AccountOMS
grant execute on object::usp_selectTEST to db_AccountOMS
grant execute on object::fn_LetterNumberRegister to db_AccountOMS
grant execute on object::fn_FullYear to db_AccountOMS
grant execute on object::usp_ReportUnLoadAccountToSMO to db_AccountOMS
grant execute on object::usp_InsertCase_ENP34 to db_AccountOMS
grant execute on object::usp_ReportAcceptedAccount to db_AccountOMS

grant execute on object::usp_SecurityService to db_AccountOMS
grant execute on object::IsCompletedCase to db_AccountOMS
grant execute on object::usp_GetsprT001 to db_AccountOMS
grant execute on object::usp_selectMedServicesReport to db_AccountOMS
grant execute on object::usp_selectMedServices to db_AccountOMS
grant execute on object::usp_selectMESForReport to db_AccountOMS
grant execute on object::usp_GetFileUnLoadKey to db_AccountOMS
grant execute on object::usp_selectDiagnosis to db_AccountOMS
grant execute on object::usp_GetFileUnLoad to db_AccountOMS
grant execute on object::usp_InsertFileSynch to db_AccountOMS
grant execute on object::usp_InsertTmpFileSynch to db_AccountOMS
grant execute on object::usp_ReportCompletedCaseAfter19 to db_AccountOMS
grant execute on object::fn_SplitNumber to db_AccountOMS
grant execute on object::fn_GetMEKRegisterCaseDB to db_AccountOMS
grant execute on object::fn_GetMEERegisterCaseDB to db_AccountOMS
grant execute on object::fn_GetEKMPRegisterCaseDB to db_AccountOMS
grant execute on object::fn_GetDS2RegisterCaseDB to db_AccountOMS
grant execute on object::fn_GetDS1RegisterCaseDB to db_AccountOMS
grant execute on object::fn_GetDS0RegisterCaseDB to db_AccountOMS
grant execute on object::usp_IsFileNameExists to db_AccountOMS
grant execute on object::usp_GetMeduslugiFromRegisterCaseDB to db_AccountOMS
grant execute on object::usp_LoadDataToHelthDepartment to db_AccountOMS
grant execute on object::IsCompletedCase2 to db_AccountOMS
grant execute on object::usp_selectCasesForReport to db_AccountOMS
grant execute on object::usp_GetFileUnLoadGUID to db_AccountOMS
grant execute on object::usp_TestAccountDataLPU to db_AccountOMS
grant execute on object::usp_selectCases_OLD to db_AccountOMS
grant execute on object::usp_GetCaseFromRegisterCaseDB to db_AccountOMS
grant execute on object::usp_TestAccountDataLPU_Test to db_AccountOMS
grant execute on object::fn_VK_CodeIndex to db_AccountOMS
grant execute on object::usp_InsertCompletedCaseIntoMeduslugi to db_AccountOMS
grant execute on object::usp_DeleteFiles to db_AccountOMS
grant execute on object::usp_ReportAmbulance_20150702 to db_AccountOMS
grant execute on object::usp_selectTreatmentResults to db_AccountOMS
grant execute on object::usp_setAddionalFilterRequest to db_AccountOMS
grant execute on object::usp_selectCasesTMP to db_AccountOMS
grant execute on object::usp_ReportPROF_O_V_MO_People to db_AccountOMS
grant execute on object::usp_Report_DDS_7 to db_AccountOMS
grant execute on object::usp_ReportDV_MO_People to db_AccountOMS
grant execute on object::usp_InsertAccountDataLPU to db_AccountOMS
grant execute on object::usp_ReportPROF_O_D_MO_People to db_AccountOMS
grant execute on object::usp_InsertAccountDataLPU_Test to db_AccountOMS
grant execute on object::fn_CheckAccount to db_AccountOMS
grant execute on object::usp_selectUslOk to db_AccountOMS
grant execute on object::usp_InsertCase_PID_ENP to db_AccountOMS
grant execute on object::usp_selectDiag to db_AccountOMS
grant execute on object::usp_selectCasesNoPersonalData to db_AccountOMS
grant execute on object::usp_selectResults to db_AccountOMS
grant execute on object::usp_Report_DDS_3 to db_AccountOMS
grant execute on object::usp_GetFiles to db_AccountOMS

grant execute on object::usp_selectProvideConditions to db_AccountOMS
grant execute on object::sp_upgraddiagrams to db_AccountOMS
grant execute on object::usp_selectReportMedServices to db_AccountOMS
grant execute on object::usp_ReportDDChild14 to db_AccountOMS
grant execute on object::usp_InsertIntoFileUser to db_AccountOMS
grant execute on object::usp_DeleteFromFileUser to db_AccountOMS
grant execute on object::sp_helpdiagrams to db_AccountOMS
grant execute on object::usp_ExistsFromFileUser to db_AccountOMS
grant execute on object::sp_helpdiagramdefinition to db_AccountOMS
grant execute on object::sp_creatediagram to db_AccountOMS
grant execute on object::sp_renamediagram to db_AccountOMS
grant execute on object::sp_alterdiagram to db_AccountOMS
grant execute on object::usp_selectReportCasesByBasicDiagnosis to db_AccountOMS
grant execute on object::sp_dropdiagram to db_AccountOMS
grant execute on object::fn_diagramobjects to db_AccountOMS
grant execute on object::usp_selectProfiles to db_AccountOMS
grant execute on object::usp_selectCases to db_AccountOMS
grant execute on object::usp_InsertFileError to db_AccountOMS
grant execute on object::usp_selectAccounts to db_AccountOMS
grant execute on object::usp_selectReportCasesMedServicesProfiles to db_AccountOMS
grant execute on object::usp_ReportCompletedCase to db_AccountOMS
grant execute on object::usp_selectReportFinishedHospitalCases to db_AccountOMS
grant execute on object::usp_GetListFilesUnLoad to db_AccountOMS
grant execute on object::usp_selectUserAvailableFilials to db_AccountOMS
grant execute on object::fn_PropertyNumberRegister to db_AccountOMS
grant execute on object::usp_IsCODEExists to db_AccountOMS
grant execute on object::usp_DeleteFile to db_AccountOMS
grant execute on object::usp_selectUserCopyPermissions to db_AccountOMS
grant execute on object::fn_PrefixNumberRegister to db_AccountOMS
grant execute on object::usp_selectUserPermissions to db_AccountOMS
grant execute on object::fn_NumberRegister to db_AccountOMS
grant execute on object::usp_ReportNotAcceptedAccount to db_AccountOMS
grant execute on object::usp_selectReportOperationsByProfileInHospital to db_AccountOMS
grant execute on object::usp_selectFilials to db_AccountOMS

