USE RegisterCases
go
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
grant select on object::tmp_PaymentAcceptedCase to db_RegisterCase
grant select on object::sprMU10UnitCode to db_RegisterCase
grant select on object::sprCodeMOUnitCode to db_RegisterCase
grant select on object::t_PlanOrders2011 to db_RegisterCase
grant select on object::View_R110 to db_RegisterCase
grant select on object::sprIteration to db_RegisterCase
grant select on object::t_FileTested to db_RegisterCase
grant select on object::t_PlanOrdersReport to db_RegisterCase
grant select on object::vw_getPatientDoc to db_RegisterCase
grant select on object::sprLPULicense to db_RegisterCase
grant select on object::t_RefCasePatientDefine to db_RegisterCase
grant select on object::t_AgeMU72_2 to db_RegisterCase
grant select on object::t_ErrorProcessControl to db_RegisterCase
grant select on object::vw_sprMU to db_RegisterCase
grant select on object::fn_PlanOrders to db_RegisterCase
grant select on object::t_CaseDefine to db_RegisterCase
grant select on object::t_CasePatientDefineIteration to db_RegisterCase
grant select on object::vw_sprMUCompletedCase to db_RegisterCase
grant select on object::POLIS to db_RegisterCase
grant select on object::vw_sprCSGTherapyMKB to db_RegisterCase
grant select on object::vw_sprCSG to db_RegisterCase
grant select on object::t_XmlElement to db_RegisterCase
grant select on object::vw_MeduslugiCSG to db_RegisterCase
grant select on object::vw_HISTPEOPLE to db_RegisterCase
grant select on object::t_CaseDefineZP1 to db_RegisterCase
grant select on object::ListPeopleFromPlotnikov to db_RegisterCase
grant select on object::sprCalendarPR_NOV0 to db_RegisterCase
grant select on object::t_SysObjects to db_RegisterCase
grant select on object::sprCalendarPR_NOV1 to db_RegisterCase
grant select on object::t_File to db_RegisterCase
grant select on object::vw_sprF08 to db_RegisterCase
grant select on object::t_CaseDefineZP1Found to db_RegisterCase
grant select on object::t_RefRegisterPatientRecordCase to db_RegisterCase
grant select on object::vw_sprF002 to db_RegisterCase
grant select on object::vw_sprOKATO to db_RegisterCase
grant select on object::vw_sprOKATOFull to db_RegisterCase
grant select on object::vw_sprV08 to db_RegisterCase
grant select on object::vw_ErrorsDescription to db_RegisterCase
grant select on object::vw_sprV002 to db_RegisterCase
grant select on object::fn_GetPID to db_RegisterCase
grant select on object::t_FileError to db_RegisterCase
grant select on object::vw_sprV004 to db_RegisterCase
grant select on object::vw_sprV010 to db_RegisterCase
grant select on object::t_XSD_Templates to db_RegisterCase
grant select on object::vw_sprPriceLevelMO to db_RegisterCase
grant select on object::vw_sprMUCompletedCaseDiagnosis to db_RegisterCase
grant select on object::vw_sprMKB10InOMS to db_RegisterCase
grant select on object::vw_test to db_RegisterCase
grant select on object::vw_dataPlanOrder to db_RegisterCase
grant select on object::vw_sprCompletedCaseMUDate to db_RegisterCase
grant select on object::vw_sprMuProfilPaymentByAge to db_RegisterCase
grant select on object::vw_sprCompletedCaseMUTariff to db_RegisterCase
grant select on object::vw_sprV006 to db_RegisterCase
grant select on object::vw_CaseNotDefineYet to db_RegisterCase
grant select on object::t_Case to db_RegisterCase
grant select on object::vw_sprNotCompletedCaseMUTariff to db_RegisterCase
grant select on object::vw_sprNotCompletedCaseMUDate to db_RegisterCase
grant select on object::vw_sprF011 to db_RegisterCase
grant select on object::t_Meduslugi_2_3 to db_RegisterCase
grant select on object::vw_sprLPUInOMS to db_RegisterCase
grant select on object::sprLPUEnableCalendar to db_RegisterCase
grant select on object::t_Diagnosis2 to db_RegisterCase
grant select on object::t_MES to db_RegisterCase
grant select on object::t_FileBackNumberOrder to db_RegisterCase
grant select on object::vw_LPUEnableCalendarPR_NOV0 to db_RegisterCase
grant select on object::t_ReasonPaymentCancelled to db_RegisterCase
grant select on object::vw_sprMKB10 to db_RegisterCase
grant select on object::vw_LPUEnableCalendarPR_NOV1 to db_RegisterCase
grant select on object::t_FinancialSanctions to db_RegisterCase
grant select on object::vw_MeduslugiMes to db_RegisterCase
grant select on object::vw_PlanOrders2011 to db_RegisterCase
grant select on object::View_meduslRC to db_RegisterCase
grant select on object::t_RegisterPatient to db_RegisterCase
grant select on object::t_RegistersCase to db_RegisterCase
grant select on object::vw_GetUnLoadPersonInPolicyDB to db_RegisterCase
grant select on object::t_Meduslugi to db_RegisterCase
grant select on object::t_FileNameError to db_RegisterCase
grant select on object::vw_sprErrorTC to db_RegisterCase
grant select on object::vw_sprErrorFLC to db_RegisterCase
grant select on object::View_RC to db_RegisterCase
grant select on object::t_UserAction to db_RegisterCase
grant select on object::t_RegisterPatientAttendant to db_RegisterCase
grant select on object::vw_sprMuWithParamAccount to db_RegisterCase
grant select on object::t_Error to db_RegisterCase
grant select on object::vw_sprCSGWithParamAccount to db_RegisterCase
grant select on object::t_RegisterPatientDocument to db_RegisterCase
grant select on object::t_RecordCase to db_RegisterCase
grant select on object::t_FileBack to db_RegisterCase
grant select on object::t_Diagnosis to db_RegisterCase
grant select on object::vw_sprMUWithAge to db_RegisterCase
grant select on object::t_PatientSMO to db_RegisterCase
grant select on object::vw_idCaseWithOutPRVSandProfilCompare to db_RegisterCase
grant select on object::vw_sprV019 to db_RegisterCase
grant select on object::t_AgeMU to db_RegisterCase
grant select on object::vw_sprV009 to db_RegisterCase
grant select on object::vw_sprV012 to db_RegisterCase
grant select on object::t_RegisterCaseBack to db_RegisterCase
grant select on object::t_Name to db_RegisterCase
grant select on object::t_RecordCaseBack to db_RegisterCase
grant select on object::t_BirthWeight to db_RegisterCase
grant select on object::vw_IsSpecialCase to db_RegisterCase
grant select on object::vw_sprMuPRVSAge to db_RegisterCase
grant select on object::t_LPUPlanOrdersDisabled to db_RegisterCase
grant select on object::vw_sprCSGSurgery to db_RegisterCase
grant select on object::vw_PeopleDefineLPU to db_RegisterCase
grant select on object::t_AgeMU2 to db_RegisterCase
grant select on object::vw_GlobalError to db_RegisterCase
grant select on object::vw_sprF012 to db_RegisterCase
grant select on object::vw_XmlTag to db_RegisterCase
grant select on object::vw_ErrorXSD to db_RegisterCase
grant select on object::vw_Polis to db_RegisterCase
grant select on object::vw_People to db_RegisterCase
grant select on object::List_1 to db_RegisterCase
grant select on object::List_PlanOrders to db_RegisterCase
grant select on object::vw_sprMUAll to db_RegisterCase
grant select on object::t_PlanOrders2011_20111213 to db_RegisterCase
grant select on object::vw_sprT001 to db_RegisterCase
grant select on object::vw_sprCSGValid to db_RegisterCase
grant select on object::vw_MES_2_78 to db_RegisterCase
grant select on object::vw_sprSMO to db_RegisterCase
grant select on object::vw_ClinicalExamination to db_RegisterCase
grant select on object::vw_sprSMOGlobal to db_RegisterCase
grant select on object::vw_sprUnit to db_RegisterCase
grant select on object::sysdiagrams to db_RegisterCase
grant select on object::vw_sprSMODisable to db_RegisterCase
grant select on object::vw_sprMUUnionV001 to db_RegisterCase
grant select on object::vw_RegisterPatient to db_RegisterCase
grant select on object::vw_Diagnosis to db_RegisterCase
grant select on object::vw_sprMUSplitByGroup to db_RegisterCase
grant select on object::vw_MSLocation to db_RegisterCase
grant select on object::vw_sprMUNotCompletedCase to db_RegisterCase
grant select on object::vw_sprMUUnionV008 to db_RegisterCase
grant select on object::t_PatientBack to db_RegisterCase
grant select on object::t_RefCaseAttachLPUItearion2 to db_RegisterCase
grant select on object::t_CaseBack to db_RegisterCase
grant select on object::t_UnreturnedCaseInAccount to db_RegisterCase
grant select on object::View_PAc to db_RegisterCase
grant select on object::vw_getFileBack to db_RegisterCase
grant select on object::vw_getIdFileNumber to db_RegisterCase


---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
grant insert on object::tmp_PaymentAcceptedCase to db_RegisterCase
grant insert on object::sprMU10UnitCode to db_RegisterCase
grant insert on object::sprCodeMOUnitCode to db_RegisterCase
grant insert on object::t_PlanOrders2011 to db_RegisterCase
grant insert on object::sprIteration to db_RegisterCase
grant insert on object::t_FileTested to db_RegisterCase
grant insert on object::t_PlanOrdersReport to db_RegisterCase
grant insert on object::sprLPULicense to db_RegisterCase
grant insert on object::t_RefCasePatientDefine to db_RegisterCase
grant insert on object::t_AgeMU72_2 to db_RegisterCase
grant insert on object::t_ErrorProcessControl to db_RegisterCase
grant insert on object::t_CaseDefine to db_RegisterCase
grant insert on object::t_CasePatientDefineIteration to db_RegisterCase
grant insert on object::POLIS to db_RegisterCase
grant insert on object::t_XmlElement to db_RegisterCase
grant insert on object::t_CaseDefineZP1 to db_RegisterCase
grant insert on object::ListPeopleFromPlotnikov to db_RegisterCase
grant insert on object::sprCalendarPR_NOV0 to db_RegisterCase
grant insert on object::t_SysObjects to db_RegisterCase
grant insert on object::sprCalendarPR_NOV1 to db_RegisterCase
grant insert on object::t_File to db_RegisterCase
grant insert on object::t_CaseDefineZP1Found to db_RegisterCase
grant insert on object::t_RefRegisterPatientRecordCase to db_RegisterCase
grant insert on object::t_FileError to db_RegisterCase
grant insert on object::t_XSD_Templates to db_RegisterCase
grant insert on object::t_Case to db_RegisterCase
grant insert on object::t_Meduslugi_2_3 to db_RegisterCase
grant insert on object::sprLPUEnableCalendar to db_RegisterCase
grant insert on object::t_Diagnosis2 to db_RegisterCase
grant insert on object::t_MES to db_RegisterCase
grant insert on object::t_FileBackNumberOrder to db_RegisterCase
grant insert on object::t_ReasonPaymentCancelled to db_RegisterCase
grant insert on object::t_FinancialSanctions to db_RegisterCase
grant insert on object::t_RegisterPatient to db_RegisterCase
grant insert on object::t_RegistersCase to db_RegisterCase
grant insert on object::t_Meduslugi to db_RegisterCase
grant insert on object::t_FileNameError to db_RegisterCase
grant insert on object::t_UserAction to db_RegisterCase
grant insert on object::t_RegisterPatientAttendant to db_RegisterCase
grant insert on object::t_Error to db_RegisterCase
grant insert on object::t_RegisterPatientDocument to db_RegisterCase
grant insert on object::t_RecordCase to db_RegisterCase
grant insert on object::t_FileBack to db_RegisterCase
grant insert on object::t_Diagnosis to db_RegisterCase
grant insert on object::t_PatientSMO to db_RegisterCase
grant insert on object::t_AgeMU to db_RegisterCase
grant insert on object::t_RegisterCaseBack to db_RegisterCase
grant insert on object::t_Name to db_RegisterCase
grant insert on object::t_RecordCaseBack to db_RegisterCase
grant insert on object::t_BirthWeight to db_RegisterCase
grant insert on object::t_LPUPlanOrdersDisabled to db_RegisterCase
grant insert on object::t_AgeMU2 to db_RegisterCase
grant insert on object::List_1 to db_RegisterCase
grant insert on object::List_PlanOrders to db_RegisterCase
grant insert on object::t_PlanOrders2011_20111213 to db_RegisterCase
grant insert on object::sysdiagrams to db_RegisterCase
grant insert on object::t_PatientBack to db_RegisterCase
grant insert on object::t_RefCaseAttachLPUItearion2 to db_RegisterCase
grant insert on object::t_CaseBack to db_RegisterCase
grant insert on object::t_UnreturnedCaseInAccount to db_RegisterCase


----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

grant execute on object::usp_GetUnreturnedCaseInAccount to db_RegisterCase
grant execute on object::fn_FullYear to db_RegisterCase
grant execute on object::usp_DefineSMOIteration1_3 to db_RegisterCase
grant execute on object::usp_DefineSMOIteration2_4 to db_RegisterCase

grant execute on object::fn_MonthName to db_RegisterCase
grant execute on object::inlist to db_RegisterCase
grant execute on object::usp_ErrorCaseMeduslugiInformation to db_RegisterCase
grant execute on object::usp_ErrorCasesInformation to db_RegisterCase
grant execute on object::usp_GetFileXSD to db_RegisterCase
grant execute on object::usp_PlanOrdersReportTotal to db_RegisterCase
grant execute on object::usp_GetsprT001 to db_RegisterCase
grant execute on object::usp_PlanOrders_1 to db_RegisterCase
grant execute on object::is_guid to db_RegisterCase
grant execute on object::usp_IsCODEExists to db_RegisterCase
grant execute on object::usp_InsertLPUEnableCalendar to db_RegisterCase
grant execute on object::usp_InsertAllLPUEnableCalendar to db_RegisterCase
grant execute on object::usp_DeleteAllLPUEnableCalendar to db_RegisterCase
grant execute on object::usp_IsFileNameExists to db_RegisterCase
grant execute on object::usp_RegisterCaseDelete to db_RegisterCase
grant execute on object::fn_GetFileNameBack2 to db_RegisterCase
grant execute on object::usp_PlanOrders to db_RegisterCase
grant execute on object::usp_GetRegisterBackInformation to db_RegisterCase
grant execute on object::usp_FillBackTables to db_RegisterCase
grant execute on object::usp_PlanOrdersReport to db_RegisterCase
grant execute on object::usp_Errors to db_RegisterCase
grant execute on object::usp_GetPlanOrders to db_RegisterCase
grant execute on object::fn_GetFileNameBack to db_RegisterCase
grant execute on object::usp_PlanOrdersReport_Test to db_RegisterCase
grant execute on object::usp_RunProcessControl2 to db_RegisterCase
grant execute on object::usp_UpdateLPUCalendarNewCase to db_RegisterCase
grant execute on object::usp_GetLPUCalendarNewCase to db_RegisterCase
grant execute on object::usp_GetPID to db_RegisterCase
grant execute on object::usp_GetFilesTMp to db_RegisterCase
grant execute on object::usp_RunProcessControl to db_RegisterCase
grant execute on object::usp_RegistrationRegisterCaseReport to db_RegisterCase
grant execute on object::usp_GetFiles to db_RegisterCase
grant execute on object::usp_SetGlobalXSDError to db_RegisterCase
grant execute on object::usp_SetGlobalError to db_RegisterCase
grant execute on object::usp_UnLoadRegisterSP_TK to db_RegisterCase
grant execute on object::GetTypePay to db_RegisterCase
grant execute on object::usp_InsertRegisterCaseDataLPU to db_RegisterCase
grant execute on object::usp_FillBackTablesAfterAllIteration to db_RegisterCase
grant execute on object::usp_RunFirstProcessControl to db_RegisterCase
grant execute on object::usp_RegisterSP_TKTest to db_RegisterCase
grant execute on object::usp_GetFileUnLoad to db_RegisterCase
grant execute on object::usp_RunRegisterSP_TK to db_RegisterCase
grant execute on object::usp_InsertRegisterCaseDataLPU_test to db_RegisterCase
grant execute on object::getPID to db_RegisterCase
grant execute on object::usp_IsDefineSMOIteration2_4Repeat to db_RegisterCase
grant execute on object::IsCompletedCase to db_RegisterCase
grant execute on object::usp_DefineSMOIteration2_4Repeat to db_RegisterCase
grant execute on object::sp_upgraddiagrams to db_RegisterCase
grant execute on object::usp_RegisterSP_TK to db_RegisterCase
grant execute on object::usp_RunRepeatTestAndDefineSMO to db_RegisterCase
grant execute on object::usp_RunTestsDefineSMOCreateSPTK to db_RegisterCase
grant execute on object::sp_helpdiagrams to db_RegisterCase
grant execute on object::sp_helpdiagramdefinition to db_RegisterCase
grant execute on object::sp_creatediagram to db_RegisterCase
grant execute on object::sp_renamediagram to db_RegisterCase
grant execute on object::sp_alterdiagram to db_RegisterCase
grant execute on object::sp_dropdiagram to db_RegisterCase
grant execute on object::fn_diagramobjects to db_RegisterCase
grant execute on object::usp_GetProcessingZP1Data to db_RegisterCase
grant execute on object::usp_IsNumberRegisterExists to db_RegisterCase
grant execute on object::usp_RunFillBackTablesAfterAllIteration to db_RegisterCase


