USE ExchangeFinancing
GO

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
grant select on object::vw_sprTypeExamination to db_ExchangeFinancing
grant select on object::t_BinaryTempAdd to db_ExchangeFinancing
grant select on object::vw_sprOrderCheckup to db_ExchangeFinancing
grant select on object::x_Parameters to db_ExchangeFinancing
grant select on object::vw_sprTypePaymentDocument to db_ExchangeFinancing
grant select on object::t_DFileOUT to db_ExchangeFinancing
grant select on object::t_ReportDebetByLPU to db_ExchangeFinancing
grant select on object::vw_SettledAccount to db_ExchangeFinancing
grant select on object::vw_CaseMO2013 to db_ExchangeFinancing
grant select on object::t_BinaryTemp to db_ExchangeFinancing
grant select on object::vw_CheckedCase to db_ExchangeFinancing
grant select on object::tmp_BinaryData to db_ExchangeFinancing
grant select on object::vw_sprFinance to db_ExchangeFinancing
grant select on object::vw_PaymentDocSMO to db_ExchangeFinancing
grant select on object::vw_DFileIn to db_ExchangeFinancing
grant select on object::vw_sprViewCalcDoc to db_ExchangeFinancing
grant select on object::vw_GetTemplate to db_ExchangeFinancing
grant select on object::vw_PaymentSMO to db_ExchangeFinancing
grant select on object::t_User to db_ExchangeFinancing
grant select on object::t_DFileDelete to db_ExchangeFinancing
grant select on object::tmp to db_ExchangeFinancing
grant select on object::vw_CheckedAcountTMP to db_ExchangeFinancing
grant select on object::tmp_ZGLV to db_ExchangeFinancing
grant select on object::vw_TypeFinance to db_ExchangeFinancing
grant select on object::tmp_DFileIn to db_ExchangeFinancing
grant select on object::vw_sprViewCalc to db_ExchangeFinancing
grant select on object::tmp_AKT to db_ExchangeFinancing
grant select on object::tmp_DFileOut to db_ExchangeFinancing
grant select on object::vw_sprViewDoc to db_ExchangeFinancing
grant select on object::tmp_SCHET to db_ExchangeFinancing
grant select on object::vw_CheckedAccount to db_ExchangeFinancing
grant select on object::tmp_SLUCH to db_ExchangeFinancing
grant select on object::tmp_Refreason to db_ExchangeFinancing
grant select on object::vw_PaymentDocTFOMS to db_ExchangeFinancing
grant select on object::vw_PaymentAcceptedAccounts to db_ExchangeFinancing
grant select on object::vw_CaseReportYearMonth to db_ExchangeFinancing
grant select on object::vw_AFileIn to db_ExchangeFinancing
grant select on object::vw_PaymentSMOFromTFOMS to db_ExchangeFinancing
grant select on object::t_AFileTested to db_ExchangeFinancing
grant select on object::t_Case2013 to db_ExchangeFinancing
grant select on object::t_Account2011 to db_ExchangeFinancing
grant select on object::vw_CaseMO to db_ExchangeFinancing
grant select on object::t_AError to db_ExchangeFinancing
grant select on object::t_Case2011 to db_ExchangeFinancing
grant select on object::t_AFileIn to db_ExchangeFinancing
grant select on object::sysdiagrams to db_ExchangeFinancing
grant select on object::vw_GetTemplateByFilial to db_ExchangeFinancing
grant select on object::View_ACCK to db_ExchangeFinancing
grant select on object::View_1 to db_ExchangeFinancing
grant select on object::View_ACCO to db_ExchangeFinancing
grant select on object::vw_sprFilial to db_ExchangeFinancing
grant select on object::vw_sprT001 to db_ExchangeFinancing
grant select on object::View_LNA to db_ExchangeFinancing
grant select on object::t_AFileDelete to db_ExchangeFinancing
grant select on object::View_ChekedSum to db_ExchangeFinancing
grant select on object::t_AFileOUT to db_ExchangeFinancing
grant select on object::View_2 to db_ExchangeFinancing
grant select on object::View_6 to db_ExchangeFinancing
grant select on object::View_3 to db_ExchangeFinancing
grant select on object::t_UserConfiguration to db_ExchangeFinancing
grant select on object::tmp_MissingCase to db_ExchangeFinancing
grant select on object::t_AFileKey to db_ExchangeFinancing
grant select on object::vw_getFilialByLogin to db_ExchangeFinancing
grant select on object::vw_ListLPUByBranch to db_ExchangeFinancing
grant select on object::View_5 to db_ExchangeFinancing
grant select on object::t_123 to db_ExchangeFinancing
grant select on object::View_4 to db_ExchangeFinancing
grant select on object::vw_sprF014 to db_ExchangeFinancing
grant select on object::t_DocumentOfCheckup to db_ExchangeFinancing
grant select on object::vw_SettledCaseTMP to db_ExchangeFinancing
grant select on object::t_ErrorRunSP to db_ExchangeFinancing
grant select on object::vw_PaymentOLD to db_ExchangeFinancing
grant select on object::vw_PaidAccount to db_ExchangeFinancing
grant select on object::t_CheckedAccount to db_ExchangeFinancing
grant select on object::t_PaymentTFOMSDeleted to db_ExchangeFinancing
grant select on object::tmp_AdditionalAmount to db_ExchangeFinancing
grant select on object::t_PaymentTFOMS to db_ExchangeFinancing
grant select on object::t_AccountRPC to db_ExchangeFinancing
grant select on object::test to db_ExchangeFinancing
grant select on object::t_PaymentSMO to db_ExchangeFinancing
grant select on object::tmp_DebetAdvance to db_ExchangeFinancing
grant select on object::t_CheckedCase to db_ExchangeFinancing
grant select on object::t_DebetAdvance to db_ExchangeFinancing
grant select on object::vw_AFileTestedWithError to db_ExchangeFinancing
grant select on object::vw_AError to db_ExchangeFinancing
grant select on object::t_DFileTested to db_ExchangeFinancing
grant select on object::vw_CheckedAccountsDeduction to db_ExchangeFinancing
grant select on object::t_ReasonDenialPayment to db_ExchangeFinancing
grant select on object::t_SSIS_Config to db_ExchangeFinancing
grant select on object::t_SSIS_LOG to db_ExchangeFinancing
grant select on object::tmp_ZGLV2 to db_ExchangeFinancing
grant select on object::vw_SSIS_Config to db_ExchangeFinancing
grant select on object::t_DError to db_ExchangeFinancing
grant select on object::tmp_PD to db_ExchangeFinancing
grant select on object::t_DeleteCheckedCase to db_ExchangeFinancing
grant select on object::t_DFileIn to db_ExchangeFinancing
grant select on object::tmp_SCHET2 to db_ExchangeFinancing
grant select on object::t_DeleteSettledCase to db_ExchangeFinancing
grant select on object::tmp_SLUCH2 to db_ExchangeFinancing
grant select on object::LN_View_7 to db_ExchangeFinancing
grant select on object::vw_CheckedCaseTMP to db_ExchangeFinancing
grant select on object::vw_AccountMO to db_ExchangeFinancing
grant select on object::vw_DError to db_ExchangeFinancing
grant select on object::vw_sprF012 to db_ExchangeFinancing
grant select on object::t_DFileKey to db_ExchangeFinancing
grant select on object::t_PaymentOLD to db_ExchangeFinancing
grant select on object::tmp_AfileDateReg to db_ExchangeFinancing
grant select on object::vw_DocumentCheckup to db_ExchangeFinancing
grant select on object::View_7 to db_ExchangeFinancing
grant select on object::vw_DFileTestedWithError to db_ExchangeFinancing
grant select on object::t_PaymentDocument to db_ExchangeFinancing
grant select on object::vw_SettledCase to db_ExchangeFinancing
grant select on object::t_SettledAccount to db_ExchangeFinancing
grant select on object::vw_sprSMO to db_ExchangeFinancing
grant select on object::vw_CheckedAccounts to db_ExchangeFinancing
grant select on object::t_SettledCase to db_ExchangeFinancing
grant select on object::vw_sprTypeCheckup to db_ExchangeFinancing


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
grant insert on object::t_BinaryTempAdd to db_ExchangeFinancing
grant insert on object::x_Parameters to db_ExchangeFinancing
grant insert on object::t_DFileOUT to db_ExchangeFinancing
grant insert on object::t_ReportDebetByLPU to db_ExchangeFinancing
grant insert on object::t_BinaryTemp to db_ExchangeFinancing
grant insert on object::tmp_BinaryData to db_ExchangeFinancing
grant insert on object::t_User to db_ExchangeFinancing
grant insert on object::t_DFileDelete to db_ExchangeFinancing
grant insert on object::tmp to db_ExchangeFinancing
grant insert on object::tmp_ZGLV to db_ExchangeFinancing
grant insert on object::tmp_DFileIn to db_ExchangeFinancing
grant insert on object::tmp_AKT to db_ExchangeFinancing
grant insert on object::tmp_DFileOut to db_ExchangeFinancing
grant insert on object::tmp_SCHET to db_ExchangeFinancing
grant insert on object::tmp_SLUCH to db_ExchangeFinancing
grant insert on object::tmp_Refreason to db_ExchangeFinancing
grant insert on object::t_AFileTested to db_ExchangeFinancing
grant insert on object::t_Case2013 to db_ExchangeFinancing
grant insert on object::t_Account2011 to db_ExchangeFinancing
grant insert on object::t_AError to db_ExchangeFinancing
grant insert on object::t_Case2011 to db_ExchangeFinancing
grant insert on object::t_AFileIn to db_ExchangeFinancing
grant insert on object::sysdiagrams to db_ExchangeFinancing
grant insert on object::t_AFileDelete to db_ExchangeFinancing
grant insert on object::t_AFileOUT to db_ExchangeFinancing
grant insert on object::t_UserConfiguration to db_ExchangeFinancing
grant insert on object::tmp_MissingCase to db_ExchangeFinancing
grant insert on object::t_AFileKey to db_ExchangeFinancing
grant insert on object::t_123 to db_ExchangeFinancing
grant insert on object::t_DocumentOfCheckup to db_ExchangeFinancing
grant insert on object::t_ErrorRunSP to db_ExchangeFinancing
grant insert on object::t_CheckedAccount to db_ExchangeFinancing
grant insert on object::t_PaymentTFOMSDeleted to db_ExchangeFinancing
grant insert on object::tmp_AdditionalAmount to db_ExchangeFinancing
grant insert on object::t_PaymentTFOMS to db_ExchangeFinancing
grant insert on object::t_AccountRPC to db_ExchangeFinancing
grant insert on object::test to db_ExchangeFinancing
grant insert on object::t_PaymentSMO to db_ExchangeFinancing
grant insert on object::tmp_DebetAdvance to db_ExchangeFinancing
grant insert on object::t_CheckedCase to db_ExchangeFinancing
grant insert on object::t_DebetAdvance to db_ExchangeFinancing
grant insert on object::t_DFileTested to db_ExchangeFinancing
grant insert on object::t_ReasonDenialPayment to db_ExchangeFinancing
grant insert on object::t_SSIS_Config to db_ExchangeFinancing
grant insert on object::t_SSIS_LOG to db_ExchangeFinancing
grant insert on object::tmp_ZGLV2 to db_ExchangeFinancing
grant insert on object::t_DError to db_ExchangeFinancing
grant insert on object::tmp_PD to db_ExchangeFinancing
grant insert on object::t_DeleteCheckedCase to db_ExchangeFinancing
grant insert on object::t_DFileIn to db_ExchangeFinancing
grant insert on object::tmp_SCHET2 to db_ExchangeFinancing
grant insert on object::t_DeleteSettledCase to db_ExchangeFinancing
grant insert on object::tmp_SLUCH2 to db_ExchangeFinancing
grant insert on object::t_DFileKey to db_ExchangeFinancing
grant insert on object::t_PaymentOLD to db_ExchangeFinancing
grant insert on object::tmp_AfileDateReg to db_ExchangeFinancing
grant insert on object::t_PaymentDocument to db_ExchangeFinancing
grant insert on object::t_SettledAccount to db_ExchangeFinancing
grant insert on object::t_SettledCase to db_ExchangeFinancing


---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
grant execute on object::usp_FinanceCalculationReport2014 to db_ExchangeFinancing
grant execute on object::RubPhrase to db_ExchangeFinancing
grant execute on object::usp_PaymetDocumentsReport to db_ExchangeFinancing
grant execute on object::usp_GetListPaymentDocument to db_ExchangeFinancing
grant execute on object::usp_FinanceActReconciliationReportLPUSMOAmbulance2014 to db_ExchangeFinancing
grant execute on object::usp_InsertAError to db_ExchangeFinancing
grant execute on object::usp_AmbulanceDocumentCheckupReport to db_ExchangeFinancing
grant execute on object::usp_GetListDocumentCheckupByAccount to db_ExchangeFinancing
grant execute on object::usp_GetAllDFileUnLoad to db_ExchangeFinancing
grant execute on object::usp_GetListPaymentDocumentByAccount to db_ExchangeFinancing
grant execute on object::usp_DocumentCheckupReport to db_ExchangeFinancing
grant execute on object::usp_AmmounAccountReport to db_ExchangeFinancing
grant execute on object::usp_GetListDocumentCheckupByFile to db_ExchangeFinancing
grant execute on object::usp_GetListPaymentDocumentByFile to db_ExchangeFinancing
grant execute on object::usp_FinanceActReconciliationReport to db_ExchangeFinancing
grant execute on object::usp_FinanceActReconciliationReportAmbulance to db_ExchangeFinancing
grant execute on object::usp_GetListSettledAccountInPayment to db_ExchangeFinancing
grant execute on object::usp_GetListDocumentCheckup to db_ExchangeFinancing
grant execute on object::usp_InsertPaymentDocumentTFOMS to db_ExchangeFinancing
grant execute on object::usp_IsPaymentSMOExist to db_ExchangeFinancing
grant execute on object::usp_UpdateAdditionalAccounts to db_ExchangeFinancing
grant execute on object::usp_UpdatePaymentDocSMONumber to db_ExchangeFinancing
grant execute on object::usp_UpdatePaymentTFOMSNumberDate to db_ExchangeFinancing
grant execute on object::usp_FinanceActionLPUReport to db_ExchangeFinancing
grant execute on object::usp_IsPaymentTFOMSExist to db_ExchangeFinancing
grant execute on object::usp_InsertBinaryTempGenaral to db_ExchangeFinancing
grant execute on object::usp_IsFileExist to db_ExchangeFinancing
grant execute on object::usp_GetListPaymentDocumentByCase to db_ExchangeFinancing
grant execute on object::usp_InsertDError to db_ExchangeFinancing
grant execute on object::usp_GetListDocumentCheckupByCase to db_ExchangeFinancing
grant execute on object::NumPhrase to db_ExchangeFinancing
grant execute on object::usp_GetAllFileUnLoad to db_ExchangeFinancing
grant execute on object::usp_GetListCaseReportYearMonth to db_ExchangeFinancing
grant execute on object::usp_GetDataForGridInPaymentDoc to db_ExchangeFinancing
grant execute on object::sp_upgraddiagrams to db_ExchangeFinancing
grant execute on object::usp_FinanceActReconciliationReportLPUSMO to db_ExchangeFinancing
grant execute on object::usp_FillDFileInFormTMPTables to db_ExchangeFinancing
grant execute on object::usp_FinanceActReconciliationReportLPUSMOAmbulance to db_ExchangeFinancing
grant execute on object::usp_ReportCodeDefectByLPU_SMO to db_ExchangeFinancing
grant execute on object::usp_InsertBinaryTemp to db_ExchangeFinancing
grant execute on object::usp_LetterSMO to db_ExchangeFinancing
grant execute on object::sp_helpdiagrams to db_ExchangeFinancing
grant execute on object::sp_helpdiagramdefinition to db_ExchangeFinancing
grant execute on object::usp_GetListSettledAccount to db_ExchangeFinancing
grant execute on object::sp_creatediagram to db_ExchangeFinancing
grant execute on object::sp_renamediagram to db_ExchangeFinancing
grant execute on object::sp_alterdiagram to db_ExchangeFinancing
grant execute on object::sp_dropdiagram to db_ExchangeFinancing
grant execute on object::fn_diagramobjects to db_ExchangeFinancing
grant execute on object::usp_InsertCodeFilialToUserConfiguration to db_ExchangeFinancing
grant execute on object::usp_GetPaymentDocumentSMOEdit to db_ExchangeFinancing
grant execute on object::usp_IsCodeFilialLogin to db_ExchangeFinancing
grant execute on object::usp_IsCodeFilialExistForLogin to db_ExchangeFinancing
grant execute on object::usp_FinanceActReconciliationReportAmbulance2014 to db_ExchangeFinancing
grant execute on object::usp_GetPaymentSMOByTFOMS to db_ExchangeFinancing
grant execute on object::usp_DocumentCheckupReportCases to db_ExchangeFinancing
grant execute on object::usp_FinanceInformationReport to db_ExchangeFinancing
grant execute on object::usp_UnloadPDInSMO to db_ExchangeFinancing
grant execute on object::usp_DeletePaymentTFOMS to db_ExchangeFinancing
grant execute on object::usp_GetDFileUnLoad to db_ExchangeFinancing
grant execute on object::usp_GetAFileUnLoad to db_ExchangeFinancing
grant execute on object::usp_GetListCheckedAccount to db_ExchangeFinancing
grant execute on object::usp_DFileInFLC to db_ExchangeFinancing
grant execute on object::usp_UnpaidAccountsReport to db_ExchangeFinancing
grant execute on object::usp_FinanceCalculationReport to db_ExchangeFinancing
grant execute on object::usp_Write_SSIS_Log to db_ExchangeFinancing
grant execute on object::usp_AFileInDelete to db_ExchangeFinancing
grant execute on object::usp_GetListAccountsFull to db_ExchangeFinancing
grant execute on object::usp_DFileInDelete to db_ExchangeFinancing
grant execute on object::usp_DFileInProcessControl to db_ExchangeFinancing
grant execute on object::usp_FinanceActReconciliationReport2014 to db_ExchangeFinancing
grant execute on object::usp_FinanceActReconciliationReportLPUSMO2014 to db_ExchangeFinancing
grant execute on object::usp_AFileInProcessControl to db_ExchangeFinancing
grant execute on object::usp_FillAFileInFormTMPTables to db_ExchangeFinancing
grant execute on object::usp_InsertRecordIntoTestTable to db_ExchangeFinancing
grant execute on object::usp_ReportFFOMS14072015 to db_ExchangeFinancing
grant execute on object::usp_AFileInFLC to db_ExchangeFinancing
grant execute on object::usp_GetOrganizationPaymentDoc to db_ExchangeFinancing
grant execute on object::usp_ReportAdditionalFinance to db_ExchangeFinancing
grant execute on object::usp_IsCodeFilialChecked to db_ExchangeFinancing

