USE RegisterCases
GO		 
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
EXEC sp_droprolemember N'db_owner', 'EAgafonova'
EXEC sp_droprolemember N'db_owner', 'NGrishin'
EXEC sp_droprolemember N'db_owner', 'PPestrecov'
EXEC sp_droprolemember N'db_owner', 'Oostapenko'
EXEC sp_droprolemember N'db_owner', 'Vbelitskaya'
EXEC sp_droprolemember N'db_owner', 'Rpolyanin'
EXEC sp_droprolemember N'db_owner', 'med\IKazmina'
EXEC sp_droprolemember N'db_owner', 'MFedesheva'
EXEC sp_droprolemember N'db_owner', 'SRomanovskii'
EXEC sp_droprolemember N'db_owner', 'EPoletkina'
EXEC sp_droprolemember N'db_owner', 'Velikanova'
EXEC sp_droprolemember N'db_owner', 'Mihailenko'
EXEC sp_droprolemember N'db_owner', 'VTFOMS\MFilin'
EXEC sp_droprolemember N'db_owner', 'VTFOMS\AStepanova'
EXEC sp_droprolemember N'db_owner', 'MED\NSemenov'
EXEC sp_droprolemember N'db_owner', 'VTFOMS\VZarya'
EXEC sp_droprolemember N'db_owner', 'VTFOMS\SSchetinin'
EXEC sp_droprolemember N'db_owner', 'sever\lsarafanova'
EXEC sp_droprolemember N'db_owner', 'VTFOMS\OGudyrin'
EXEC sp_droprolemember N'db_owner', 'VTFOMS\ATravov'
EXEC sp_droprolemember N'db_owner', 'med\EPolyakova'
EXEC sp_droprolemember N'db_owner', 'VTFOMS\lkarpenko'
EXEC sp_droprolemember N'db_owner', 'SEVER\VBurlachenko'
EXEC sp_droprolemember N'db_owner', 'AKrehov'
EXEC sp_droprolemember N'db_owner', 'VTFOMS\esushich'

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
EXEC sp_addrolemember N'db_RegisterCase', 'EAgafonova'
EXEC sp_addrolemember N'db_RegisterCase', 'NGrishin'
EXEC sp_addrolemember N'db_RegisterCase', 'PPestrecov'
EXEC sp_addrolemember N'db_RegisterCase', 'Oostapenko'
EXEC sp_addrolemember N'db_RegisterCase', 'Vbelitskaya'
EXEC sp_addrolemember N'db_RegisterCase', 'Rpolyanin'
EXEC sp_addrolemember N'db_RegisterCase', 'med\IKazmina'
EXEC sp_addrolemember N'db_RegisterCase', 'MFedesheva'
EXEC sp_addrolemember N'db_RegisterCase', 'SRomanovskii'
EXEC sp_addrolemember N'db_RegisterCase', 'EPoletkina'
EXEC sp_addrolemember N'db_RegisterCase', 'Velikanova'
EXEC sp_addrolemember N'db_RegisterCase', 'Mihailenko'
EXEC sp_addrolemember N'db_RegisterCase', 'VTFOMS\MFilin'
EXEC sp_addrolemember N'db_RegisterCase', 'VTFOMS\AStepanova'
EXEC sp_addrolemember N'db_RegisterCase', 'MED\NSemenov'
EXEC sp_addrolemember N'db_RegisterCase', 'VTFOMS\VZarya'
EXEC sp_addrolemember N'db_RegisterCase', 'VTFOMS\SSchetinin'
EXEC sp_addrolemember N'db_RegisterCase', 'sever\lsarafanova'
EXEC sp_addrolemember N'db_RegisterCase', 'VTFOMS\OGudyrin'
EXEC sp_addrolemember N'db_RegisterCase', 'VTFOMS\ATravov'
EXEC sp_addrolemember N'db_RegisterCase', 'med\EPolyakova'
EXEC sp_addrolemember N'db_RegisterCase', 'VTFOMS\lkarpenko'
EXEC sp_addrolemember N'db_RegisterCase', 'SEVER\VBurlachenko'
EXEC sp_addrolemember N'db_RegisterCase', 'AKrehov'
EXEC sp_addrolemember N'db_RegisterCase', 'VTFOMS\esushich'