use PolicyRegister
go
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[PEOPLE]') AND name = N'IX_HISTUDL_DOCN')
DROP INDEX [IX_HISTUDL_DOCN] ON [dbo].[HISTUDL] WITH ( ONLINE = OFF )
go
create nonclustered index IX_HISTUDL_DOCN on dbo.HISTUDL(PID) INCLUDE(DOCN) 
go
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[PEOPLE]') AND name = N'IX_HISTFDR_FAM_IM_OT_DR')
DROP INDEX [IX_HISTFDR_FAM_IM_OT_DR] ON [dbo].[HISTFDR] WITH ( ONLINE = OFF )
go
create nonclustered index IX_HISTFDR_FAM_IM_OT_DR on dbo.HISTFDR(PID,FAM,IM,OT,DR) 
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
go
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[PEOPLE]') AND name = N'IX_PEOPLE_DR')
DROP INDEX [IX_PEOPLE_DR] ON [dbo].[PEOPLE] WITH ( ONLINE = OFF )
go
CREATE NONCLUSTERED INDEX [IX_PEOPLE_DR] ON [dbo].[PEOPLE] 
(
	[DR] ASC,
	IM
)INCLUDE(FAM,OT) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
go
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[PEOPLE]') AND name = N'IX_PEOPLE_FIODR_DOCN_Cases')
DROP INDEX [IX_PEOPLE_FIODR_DOCN_Cases] ON [dbo].[PEOPLE] WITH ( ONLINE = OFF )

/****** Object:  Index [IX_PEOPLE_FIODR_DOCN_Cases]    Script Date: 03/05/2012 08:20:43 ******/
CREATE NONCLUSTERED INDEX [IX_PEOPLE_FIODR_DOCN_Cases] ON [dbo].[PEOPLE] 
(
	[FAM] ASC,
	[IM] ASC,
	[OT] ASC,
	[DR] ASC
)
INCLUDE ( [DOCN]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

/****** Object:  Index [IX_PEOPLE_IM_OT_DR_DOCN_Case]    Script Date: 03/05/2012 08:21:05 ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[PEOPLE]') AND name = N'IX_PEOPLE_IM_OT_DR_DOCN_Case')
DROP INDEX [IX_PEOPLE_IM_OT_DR_DOCN_Case] ON [dbo].[PEOPLE] WITH ( ONLINE = OFF )
GO
CREATE NONCLUSTERED INDEX [IX_PEOPLE_IM_OT_DR_DOCN_Case] ON [dbo].[PEOPLE] 
(
	[DOCN] ASC
)
INCLUDE ( [IM],
[OT],
[DR],
[FAM]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_PEOPLE_SS_FAM_OT_IM_Case]    Script Date: 03/05/2012 08:21:38 ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[PEOPLE]') AND name = N'IX_PEOPLE_SS_FAM_OT_IM_Case')
DROP INDEX [IX_PEOPLE_SS_FAM_OT_IM_Case] ON [dbo].[PEOPLE] WITH ( ONLINE = OFF )
GO
CREATE NONCLUSTERED INDEX [IX_PEOPLE_SS_FAM_OT_IM_Case] ON [dbo].[PEOPLE] 
(
	[SS] ASC,
	[FAM] ASC,
	[IM] ASC,
	[OT] ASC
)
INCLUDE ( [DR]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_PEOPLE_SS_FAM_DOCN_IM_DR_Case]    Script Date: 03/05/2012 08:33:09 ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[PEOPLE]') AND name = N'IX_PEOPLE_SS_FAM_DOCN_IM_DR_Case')
DROP INDEX [IX_PEOPLE_SS_FAM_DOCN_IM_DR_Case] ON [dbo].[PEOPLE] WITH ( ONLINE = OFF )
GO
CREATE NONCLUSTERED INDEX [IX_PEOPLE_SS_FAM_DOCN_IM_DR_Case] ON [dbo].[PEOPLE] 
(
	[SS] ASC,
	[FAM] ASC,
	[IM] ASC,
	[OT] ASC,
	[DR] ASC,
	[DOCN] ASC
)
INCLUDE ( [PID]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO




