CREATE TABLE #tDS
	(
		IDCASE int,
		ID_C uniqueidentifier,
		DS varchar(10), 
		TypeDiagnosis TINYINT, 
		SL_ID UNIQUEIDENTIFIER
	 )

CREATE TABLE #tBW
	(
		IDCASE int,
		ID_C uniqueidentifier, 
		BirthWeight SMALLINT, 
		SL_ID UNIQUEIDENTIFIER
	)

CREATE TABLE #tCoeff
	(
		IDCASE BIGINT,
		ID_C uniqueidentifier, 
		CODE_SL SMALLINT,
		VAL_C DECIMAL(3,2), 
		SL_ID UNIQUEIDENTIFIER
	)

CREATE TABLE #tKiro
	(
		IDCASE BIGINT,
		ID_C UNIQUEIDENTIFIER,
		CODE_KIRO INT, 
		VAL_K DECIMAL(3,2), 
		SL_ID UNIQUEIDENTIFIER
	)
--16.07.2018
CREATE TABLE #ONK_SL
	(
		IDCASE int,
		ID_C UNIQUEIDENTIFIER,
		DS1_T TINYINT,
		STAD SMALLINT, 
		ONK_T SMALLINT,
		ONK_N SMALLINT,
		ONK_M SMALLINT,
		MTSTZ TINYINT,
		SOD DECIMAL(5,2),						
		SL_ID UNIQUEIDENTIFIER						
	)
CREATE TABLE #B_DIAG
	(
		IDCASE int,
		ID_C UNIQUEIDENTIFIER,
		DIAG_TIP TINYINT,
		DIAG_CODE SMALLINT, 
		DIAG_RSLT SMALLINT, 
		DIAG_DATE date, 
		SL_ID UNIQUEIDENTIFIER, 
		REC_RSLT TINYINT
	)
CREATE TABLE #B_PROT
	(
		IDCASE int,
		ID_C UNIQUEIDENTIFIER,
		PROT TINYINT,
		D_PROT DATE, 
		SL_ID UNIQUEIDENTIFIER
	)
						
create table #NAPR
	(
		IDCASE int,
		ID_C uniqueidentifier,
		NAPR_DATE DATE, 
		NAPR_MO VARCHAR(6),
		NAPR_V TINYINT,
		MET_ISSL TINYINT,
		NAPR_USL VARCHAR(15), 
		SL_ID UNIQUEIDENTIFIER
	)
create table #CONS
	(
		IDCASE int,
		ID_C uniqueidentifier,
		SL_ID UNIQUEIDENTIFIER,
		PR_CONS TINYINT, 
		DT_CONS DATE
	)

create table #KSG_KPG
	(
		IDCASE int,
		ID_C uniqueidentifier,
		SL_ID UNIQUEIDENTIFIER,
		N_KSG VARCHAR(20),
		DKK1 VARCHAR(10),
		DKK2 VARCHAR(10),
		SL_K TINYINT,
		IT_SL DECIMAL(3,2)
	)

create table #ONK_USL
	(
		IDCASE int,
		ID_C uniqueidentifier,
		SL_ID UNIQUEIDENTIFIER,		
		USL_TIP TINYINT, 
		HIR_TIP TINYINT, 
		LEK_TIP_L TINYINT,
		LEK_TIP_V TINYINT,
		LUCH_TIP TINYINT,
   )      

create table #LEK_PR
	(
		IDCASE int,
		ID_C uniqueidentifier,
		SL_ID UNIQUEIDENTIFIER,		
		USL_TIP TINYINT, 
		REGNUM NVARCHAR(40),
		DATE_INJ DATE
   )      

